// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: engine.proto

package main

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EngineService_Ping_FullMethodName         = "/engine.EngineService/Ping"
	EngineService_StartRun_FullMethodName     = "/engine.EngineService/StartRun"
	EngineService_GetRunStatus_FullMethodName = "/engine.EngineService/GetRunStatus"
	EngineService_CancelRun_FullMethodName    = "/engine.EngineService/CancelRun"
	EngineService_ResumeRun_FullMethodName    = "/engine.EngineService/ResumeRun"
)

// EngineServiceClient is the client API for EngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EngineServiceClient interface {
	// Ping returns a pong response for health checking
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// StartRun begins executing a workflow graph
	StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error)
	// GetRunStatus returns the current status of a run
	GetRunStatus(ctx context.Context, in *GetRunStatusRequest, opts ...grpc.CallOption) (*GetRunStatusResponse, error)
	// CancelRun cancels an active run
	CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error)
	// ResumeRun resumes a paused run (e.g., after human gate approval)
	ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error)
}

type engineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineServiceClient(cc grpc.ClientConnInterface) EngineServiceClient {
	return &engineServiceClient{cc}
}

func (c *engineServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, EngineService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) StartRun(ctx context.Context, in *StartRunRequest, opts ...grpc.CallOption) (*StartRunResponse, error) {
	out := new(StartRunResponse)
	err := c.cc.Invoke(ctx, EngineService_StartRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) GetRunStatus(ctx context.Context, in *GetRunStatusRequest, opts ...grpc.CallOption) (*GetRunStatusResponse, error) {
	out := new(GetRunStatusResponse)
	err := c.cc.Invoke(ctx, EngineService_GetRunStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) CancelRun(ctx context.Context, in *CancelRunRequest, opts ...grpc.CallOption) (*CancelRunResponse, error) {
	out := new(CancelRunResponse)
	err := c.cc.Invoke(ctx, EngineService_CancelRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineServiceClient) ResumeRun(ctx context.Context, in *ResumeRunRequest, opts ...grpc.CallOption) (*ResumeRunResponse, error) {
	out := new(ResumeRunResponse)
	err := c.cc.Invoke(ctx, EngineService_ResumeRun_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServiceServer is the server API for EngineService service.
// All implementations must embed UnimplementedEngineServiceServer
// for forward compatibility
type EngineServiceServer interface {
	// Ping returns a pong response for health checking
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// StartRun begins executing a workflow graph
	StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error)
	// GetRunStatus returns the current status of a run
	GetRunStatus(context.Context, *GetRunStatusRequest) (*GetRunStatusResponse, error)
	// CancelRun cancels an active run
	CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error)
	// ResumeRun resumes a paused run (e.g., after human gate approval)
	ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error)
	mustEmbedUnimplementedEngineServiceServer()
}

// UnimplementedEngineServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEngineServiceServer struct {
}

func (UnimplementedEngineServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedEngineServiceServer) StartRun(context.Context, *StartRunRequest) (*StartRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRun not implemented")
}
func (UnimplementedEngineServiceServer) GetRunStatus(context.Context, *GetRunStatusRequest) (*GetRunStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRunStatus not implemented")
}
func (UnimplementedEngineServiceServer) CancelRun(context.Context, *CancelRunRequest) (*CancelRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRun not implemented")
}
func (UnimplementedEngineServiceServer) ResumeRun(context.Context, *ResumeRunRequest) (*ResumeRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResumeRun not implemented")
}
func (UnimplementedEngineServiceServer) mustEmbedUnimplementedEngineServiceServer() {}

// UnsafeEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngineServiceServer will
// result in compilation errors.
type UnsafeEngineServiceServer interface {
	mustEmbedUnimplementedEngineServiceServer()
}

func RegisterEngineServiceServer(s grpc.ServiceRegistrar, srv EngineServiceServer) {
	s.RegisterService(&EngineService_ServiceDesc, srv)
}

func _EngineService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_StartRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).StartRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_StartRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).StartRun(ctx, req.(*StartRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_GetRunStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRunStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).GetRunStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_GetRunStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).GetRunStatus(ctx, req.(*GetRunStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_CancelRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).CancelRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_CancelRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).CancelRun(ctx, req.(*CancelRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EngineService_ResumeRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServiceServer).ResumeRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EngineService_ResumeRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServiceServer).ResumeRun(ctx, req.(*ResumeRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EngineService_ServiceDesc is the grpc.ServiceDesc for EngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.EngineService",
	HandlerType: (*EngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _EngineService_Ping_Handler,
		},
		{
			MethodName: "StartRun",
			Handler:    _EngineService_StartRun_Handler,
		},
		{
			MethodName: "GetRunStatus",
			Handler:    _EngineService_GetRunStatus_Handler,
		},
		{
			MethodName: "CancelRun",
			Handler:    _EngineService_CancelRun_Handler,
		},
		{
			MethodName: "ResumeRun",
			Handler:    _EngineService_ResumeRun_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}

const (
	MemoryService_RetrieveMemory_FullMethodName     = "/engine.MemoryService/RetrieveMemory"
	MemoryService_SaveObservation_FullMethodName    = "/engine.MemoryService/SaveObservation"
	MemoryService_SearchObservations_FullMethodName = "/engine.MemoryService/SearchObservations"
	MemoryService_GetObservation_FullMethodName     = "/engine.MemoryService/GetObservation"
	MemoryService_GetContext_FullMethodName         = "/engine.MemoryService/GetContext"
	MemoryService_GetTimeline_FullMethodName        = "/engine.MemoryService/GetTimeline"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MemoryServiceClient interface {
	// RetrieveMemory returns relevant memory chunks for a query.
	RetrieveMemory(ctx context.Context, in *RetrieveMemoryRequest, opts ...grpc.CallOption) (*RetrieveMemoryResponse, error)
	// SaveObservation creates or updates a curated memory observation.
	SaveObservation(ctx context.Context, in *SaveObservationRequest, opts ...grpc.CallOption) (*SaveObservationResponse, error)
	// SearchObservations returns curated observations matching the query and scope.
	SearchObservations(ctx context.Context, in *SearchObservationsRequest, opts ...grpc.CallOption) (*SearchObservationsResponse, error)
	// GetObservation returns a single curated observation by ID.
	GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error)
	// GetContext returns context-ready curated observations and retrieval strategy metadata.
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
	// GetTimeline returns recent curated observations ordered by recency.
	GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) RetrieveMemory(ctx context.Context, in *RetrieveMemoryRequest, opts ...grpc.CallOption) (*RetrieveMemoryResponse, error) {
	out := new(RetrieveMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_RetrieveMemory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SaveObservation(ctx context.Context, in *SaveObservationRequest, opts ...grpc.CallOption) (*SaveObservationResponse, error) {
	out := new(SaveObservationResponse)
	err := c.cc.Invoke(ctx, MemoryService_SaveObservation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SearchObservations(ctx context.Context, in *SearchObservationsRequest, opts ...grpc.CallOption) (*SearchObservationsResponse, error) {
	out := new(SearchObservationsResponse)
	err := c.cc.Invoke(ctx, MemoryService_SearchObservations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetObservation(ctx context.Context, in *GetObservationRequest, opts ...grpc.CallOption) (*GetObservationResponse, error) {
	out := new(GetObservationResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetObservation_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetContext_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetTimeline(ctx context.Context, in *GetTimelineRequest, opts ...grpc.CallOption) (*GetTimelineResponse, error) {
	out := new(GetTimelineResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetTimeline_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility
type MemoryServiceServer interface {
	// RetrieveMemory returns relevant memory chunks for a query.
	RetrieveMemory(context.Context, *RetrieveMemoryRequest) (*RetrieveMemoryResponse, error)
	// SaveObservation creates or updates a curated memory observation.
	SaveObservation(context.Context, *SaveObservationRequest) (*SaveObservationResponse, error)
	// SearchObservations returns curated observations matching the query and scope.
	SearchObservations(context.Context, *SearchObservationsRequest) (*SearchObservationsResponse, error)
	// GetObservation returns a single curated observation by ID.
	GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error)
	// GetContext returns context-ready curated observations and retrieval strategy metadata.
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	// GetTimeline returns recent curated observations ordered by recency.
	GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error)
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMemoryServiceServer struct {
}

func (UnimplementedMemoryServiceServer) RetrieveMemory(context.Context, *RetrieveMemoryRequest) (*RetrieveMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RetrieveMemory not implemented")
}
func (UnimplementedMemoryServiceServer) SaveObservation(context.Context, *SaveObservationRequest) (*SaveObservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveObservation not implemented")
}
func (UnimplementedMemoryServiceServer) SearchObservations(context.Context, *SearchObservationsRequest) (*SearchObservationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchObservations not implemented")
}
func (UnimplementedMemoryServiceServer) GetObservation(context.Context, *GetObservationRequest) (*GetObservationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObservation not implemented")
}
func (UnimplementedMemoryServiceServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedMemoryServiceServer) GetTimeline(context.Context, *GetTimelineRequest) (*GetTimelineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTimeline not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_RetrieveMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrieveMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).RetrieveMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_RetrieveMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).RetrieveMemory(ctx, req.(*RetrieveMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SaveObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SaveObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SaveObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SaveObservation(ctx, req.(*SaveObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SearchObservations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchObservationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SearchObservations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SearchObservations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SearchObservations(ctx, req.(*SearchObservationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetObservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetObservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetObservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetObservation(ctx, req.(*GetObservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetTimeline_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimelineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetTimeline(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetTimeline_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetTimeline(ctx, req.(*GetTimelineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engine.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrieveMemory",
			Handler:    _MemoryService_RetrieveMemory_Handler,
		},
		{
			MethodName: "SaveObservation",
			Handler:    _MemoryService_SaveObservation_Handler,
		},
		{
			MethodName: "SearchObservations",
			Handler:    _MemoryService_SearchObservations_Handler,
		},
		{
			MethodName: "GetObservation",
			Handler:    _MemoryService_GetObservation_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _MemoryService_GetContext_Handler,
		},
		{
			MethodName: "GetTimeline",
			Handler:    _MemoryService_GetTimeline_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
