# Generated by Django 6.0.1 on 2026-01-27 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0005_apikey"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunCheckpoint",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="checkpoint",
                        serialize=False,
                        to="orm.run",
                    ),
                ),
                ("node_id", models.CharField(max_length=64)),
                ("step_index", models.PositiveIntegerField(default=0)),
                ("state_json", models.JSONField(default=dict)),
                ("completed_nodes", models.JSONField(default=list)),
                ("skipped_nodes", models.JSONField(default=list)),
                ("graph_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "run_checkpoints",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["updated_at"], name="run_checkpoints_updated_idx"),
                ],
            },
        ),
    ]
