# Generated by Django 6.0.1 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0006_run_checkpoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="NodeRunCache",
            fields=[
                ("cache_key", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("output_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "db_table": "node_run_cache",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(fields=["expires_at"], name="node_run_cache_expires_idx"),
                ],
            },
        ),
    ]
