# Generated by Django 6.0.1 on 2026-01-27 00:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0007_node_run_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("event_type", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orm.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_events",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["run", "created_at"], name="run_events_run_time_idx"),
                ],
            },
        ),
    ]
