# Generated by Django 6.0.1 on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0008_run_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="thread_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["owner", "thread_id"], name="runs_owner_thread_idx"),
        ),
    ]
