# Generated by Django 6.0.1 on 2026-01-27 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0009_run_thread_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                ("namespace", models.CharField(max_length=255, default="global")),
                ("key", models.CharField(max_length=255)),
                ("value_json", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField(null=True, blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "memory_entries",
                "indexes": [
                    models.Index(fields=["namespace", "key"], name="memory_entries_ns_key_idx"),
                    models.Index(fields=["expires_at"], name="memory_entries_exp_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["namespace", "key"], name="memory_entries_ns_key_uniq"
                    ),
                ],
            },
        ),
    ]
