# Generated by Django 6.0.1 on 2026-01-30 00:00

import uuid

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0010_memory_entries"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryConfiguration",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("buffer_enabled", models.BooleanField(default=True)),
                ("buffer_size", models.PositiveIntegerField(default=20)),
                ("auto_prepend", models.BooleanField(default=True)),
                ("redis_enabled", models.BooleanField(default=False)),
                ("redis_summary_ttl", models.PositiveIntegerField(default=86400)),
                ("redis_facts_ttl", models.PositiveIntegerField(default=604800)),
                ("vector_enabled", models.BooleanField(default=False)),
                ("vector_top_k", models.PositiveIntegerField(default=5)),
                ("vector_threshold", models.FloatField(default=0.7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graph",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="memory_config",
                        to="orm.graph",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=models.CASCADE,
                        related_name="default_memory_config",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "memory_configurations",
                "constraints": [
                    models.CheckConstraint(
                        condition=~(models.Q(graph__isnull=True) & models.Q(user__isnull=True)),
                        name="memory_config_requires_scope",
                    ),
                    models.CheckConstraint(
                        condition=~(models.Q(graph__isnull=False) & models.Q(user__isnull=False)),
                        name="memory_config_single_scope",
                    ),
                ],
            },
        ),
    ]
