# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0011_memory_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="memoryconfiguration",
            name="summarization_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="memoryconfiguration",
            name="summarization_threshold",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="memoryconfiguration",
            name="summarization_keep_recent",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="memoryconfiguration",
            name="summarization_model",
            field=models.CharField(default="gpt-4", max_length=50),
        ),
    ]
