# Generated by Django 6.0.1 on 2026-01-30 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0012_summarization_config"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryUsage",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("tenant_id", models.UUIDField()),
                ("usage_date", models.DateField()),
                ("summarization_prompt_tokens", models.PositiveIntegerField(default=0)),
                ("summarization_completion_tokens", models.PositiveIntegerField(default=0)),
                ("summarization_total_tokens", models.PositiveIntegerField(default=0)),
                ("summarization_cost_usd", models.DecimalField(default=0, max_digits=12, decimal_places=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "memory_usage",
                "ordering": ["-usage_date"],
            },
        ),
        migrations.AddConstraint(
            model_name="memoryusage",
            constraint=models.UniqueConstraint(
                fields=("tenant_id", "usage_date"),
                name="memory_usage_tenant_date_uniq",
            ),
        ),
    ]
