# Generated by Django 6.0.1 on 2026-01-30 00:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0013_memory_usage"),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
        ),
    ]
