# Generated by Django 6.0.1 on 2026-01-30 00:00

import uuid

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0014_pgvector_setup"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemoryChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, default=uuid.uuid4, editable=False, serialize=False
                    ),
                ),
                ("tenant_id", models.UUIDField(db_index=True)),
                ("agent_id", models.UUIDField(blank=True, null=True, db_index=True)),
                ("run_id", models.UUIDField(blank=True, null=True, db_index=True)),
                ("session_id", models.UUIDField(blank=True, null=True, db_index=True)),
                ("content", models.TextField()),
                ("chunk_type", models.CharField(max_length=20)),
                ("metadata", models.JSONField(default=dict, blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1536)),
                ("embedding_model", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("source_timestamp", models.DateTimeField()),
            ],
            options={
                "db_table": "memory_chunks",
            },
        ),
        migrations.AddIndex(
            model_name="memorychunk",
            index=models.Index(fields=["tenant_id"], name="memory_chunks_tenant_idx"),
        ),
        migrations.AddIndex(
            model_name="memorychunk",
            index=models.Index(fields=["tenant_id", "agent_id"], name="memory_chunks_agent_idx"),
        ),
        migrations.AddIndex(
            model_name="memorychunk",
            index=models.Index(fields=["tenant_id", "run_id"], name="memory_chunks_run_idx"),
        ),
        migrations.AddIndex(
            model_name="memorychunk",
            index=models.Index(
                fields=["tenant_id", "session_id"], name="memory_chunks_session_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="memorychunk",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                name="memory_chunks_embedding_ivfflat",
                lists=100,
            ),
        ),
    ]
