# Generated by Django 6.0.1 on 2026-04-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0041_memory_observations"),
    ]

    operations = [
        migrations.AddField(
            model_name="noderun",
            name="span_id",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="noderun",
            name="trace_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="run",
            name="trace_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="runevent",
            name="span_id",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="runevent",
            name="trace_id",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddIndex(
            model_name="noderun",
            index=models.Index(fields=["trace_id"], name="node_runs_trace_id_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["trace_id"], name="runs_trace_id_idx"),
        ),
        migrations.AddIndex(
            model_name="runevent",
            index=models.Index(fields=["trace_id"], name="run_events_trace_id_idx"),
        ),
    ]
