# Generated by Django 4.2.3 on 2026-04-05 13:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0043_agentregistryentry_decisionrecord_taskrecord_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RunEventProjection",
            fields=[
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("paused", "Paused"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("output_json", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("pause_state_json", models.JSONField(blank=True, null=True)),
                ("paused_node_id", models.CharField(blank=True, max_length=64, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=32)),
                ("last_event_id", models.CharField(blank=True, default="", max_length=64)),
                ("last_event_type", models.CharField(blank=True, default="", max_length=64)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="event_projection",
                        serialize=False,
                        to="orm.run",
                    ),
                ),
            ],
            options={
                "db_table": "run_event_projections",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="NodeRunEventProjection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("node_id", models.CharField(max_length=255)),
                ("node_type", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("waiting", "Waiting"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("attempt", models.PositiveIntegerField(default=1)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("output_json", models.JSONField(blank=True, null=True)),
                ("error_json", models.JSONField(blank=True, null=True)),
                ("trace_id", models.CharField(blank=True, default="", max_length=32)),
                ("span_id", models.CharField(blank=True, default="", max_length=16)),
                ("last_event_id", models.CharField(blank=True, default="", max_length=64)),
                ("last_event_type", models.CharField(blank=True, default="", max_length=64)),
                ("last_event_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="node_event_projections",
                        to="orm.run",
                    ),
                ),
            ],
            options={
                "db_table": "node_run_event_projections",
                "ordering": ["started_at", "attempt"],
            },
        ),
        migrations.AddIndex(
            model_name="runeventprojection",
            index=models.Index(
                fields=["status", "updated_at"], name="run_evt_proj_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="runeventprojection",
            index=models.Index(fields=["trace_id"], name="run_evt_proj_trace_idx"),
        ),
        migrations.AddIndex(
            model_name="runeventprojection",
            index=models.Index(fields=["last_event_at"], name="run_evt_proj_event_at_idx"),
        ),
        migrations.AddIndex(
            model_name="noderuneventprojection",
            index=models.Index(
                fields=["run", "started_at", "attempt"],
                name="node_evt_proj_run_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="noderuneventprojection",
            index=models.Index(fields=["trace_id"], name="node_evt_proj_trace_idx"),
        ),
        migrations.AddIndex(
            model_name="noderuneventprojection",
            index=models.Index(
                fields=["last_event_at"], name="node_evt_proj_event_at_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="noderuneventprojection",
            constraint=models.UniqueConstraint(
                fields=("run", "node_id", "attempt"),
                name="node_evt_proj_run_node_attempt_uniq",
            ),
        ),
    ]
