# Generated by Django 4.2.3 on 2026-04-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0044_run_event_shadow_projections"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="engine_instance_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="run",
            name="last_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="run",
            name="recovery_state",
            field=models.CharField(blank=True, default="idle", max_length=32),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["last_progress_at"], name="runs_progress_idx"),
        ),
        migrations.AddIndex(
            model_name="run",
            index=models.Index(fields=["recovery_state"], name="runs_recovery_state_idx"),
        ),
    ]
