# Generated by Django 4.2.3 on 2026-04-27 20:26

from django.db import migrations, models
import django.db.models.deletion


def backfill_organization_scopes(apps, schema_editor):
    graph_model = apps.get_model('orm', 'Graph')
    prompt_model = apps.get_model('orm', 'PromptTemplate')
    run_model = apps.get_model('orm', 'Run')

    for graph in graph_model.objects.filter(organization__isnull=True).select_related('owner').iterator():
        organization_id = getattr(graph.owner, 'default_organization_id', None)
        if organization_id:
            graph_model.objects.filter(pk=graph.pk, organization__isnull=True).update(
                organization_id=organization_id,
            )

    for prompt in prompt_model.objects.filter(
        organization__isnull=True,
        owner__isnull=False,
    ).select_related('owner').iterator():
        organization_id = getattr(prompt.owner, 'default_organization_id', None)
        if organization_id:
            prompt_model.objects.filter(pk=prompt.pk, organization__isnull=True).update(
                organization_id=organization_id,
            )

    for run in run_model.objects.filter(organization__isnull=True).select_related(
        'owner',
        'graph_version__graph',
    ).iterator():
        organization_id = getattr(run.graph_version.graph, 'organization_id', None)
        if not organization_id:
            organization_id = getattr(run.owner, 'default_organization_id', None)
        if organization_id:
            run_model.objects.filter(pk=run.pk, organization__isnull=True).update(
                organization_id=organization_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0050_tool_executions'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graphs', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='prompttemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompt_templates', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='run',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='orm.organization'),
        ),
        migrations.RunPython(backfill_organization_scopes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='graph',
            index=models.Index(fields=['organization', 'updated_at'], name='graphs_org_updated_idx'),
        ),
        migrations.AddIndex(
            model_name='prompttemplate',
            index=models.Index(fields=['organization', 'created_at'], name='prompt_templates_org_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['organization', 'started_at'], name='runs_org_started_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['organization', 'status'], name='runs_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='run',
            index=models.Index(fields=['organization', 'thread_id'], name='runs_org_thread_idx'),
        ),
        migrations.AddConstraint(
            model_name='graph',
            constraint=models.UniqueConstraint(condition=models.Q(('external_ref__gt', ''), ('organization__isnull', False)), fields=('organization', 'external_source', 'external_ref'), name='graphs_org_source_external_ref_unique'),
        ),
    ]
