# Generated by ForgeGraph implementation work.

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0052_ensure_default_organizations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingBriefRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("objective", models.TextField(blank=True, null=True)),
                ("deliverable", models.TextField(blank=True, null=True)),
                ("constraints_json", models.JSONField(blank=True, default=list)),
                ("success_criteria_json", models.JSONField(blank=True, default=list)),
                ("stakeholders_json", models.JSONField(blank=True, default=list)),
                ("dependencies_json", models.JSONField(blank=True, default=list)),
                ("assumptions_json", models.JSONField(blank=True, default=list)),
                ("clarifications_json", models.JSONField(blank=True, default=list)),
                ("priority_frame_json", models.JSONField(blank=True, default=dict)),
                (
                    "autonomy_mode",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("assisted", "Assisted"),
                            ("autonomous", "Autonomous"),
                        ],
                        default="assisted",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_briefs",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_operating_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_briefs",
                        to="orm.run",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_briefs",
                        to="orm.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_operating_briefs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "operating_briefs",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="InteractionEventRecord",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("sequence", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("MODIFY", "Modify"),
                            ("CLARIFY", "Clarify"),
                            ("CONSTRAINT", "Constraint"),
                            ("PRIORITY_SHIFT", "Priority Shift"),
                            ("APPROVE", "Approve"),
                            ("OVERRIDE", "Override"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "actor",
                    models.CharField(
                        choices=[("user", "User"), ("system", "System")],
                        max_length=16,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("raw_input", models.TextField(blank=True, default="")),
                ("delta_json", models.JSONField(blank=True, default=dict)),
                ("affected_fields_json", models.JSONField(blank=True, default=list)),
                ("interpretation_json", models.JSONField(blank=True, default=dict)),
                (
                    "pm_action",
                    models.CharField(
                        choices=[
                            ("EXECUTE", "Execute"),
                            ("ASK_CLARIFICATION", "Ask Clarification"),
                            ("ASSUME_AND_CONTINUE", "Assume And Continue"),
                            ("BLOCK", "Block"),
                        ],
                        max_length=32,
                    ),
                ),
                ("plan_implications_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interaction_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "brief",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="orm.operatingbriefrecord",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="orm.graph",
                    ),
                ),
                (
                    "operation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="orm.run",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interaction_events",
                        to="orm.organization",
                    ),
                ),
            ],
            options={
                "db_table": "interaction_events",
                "ordering": ["brief", "sequence"],
            },
        ),
        migrations.AddIndex(
            model_name="operatingbriefrecord",
            index=models.Index(fields=["organization", "updated_at"], name="op_briefs_org_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="operatingbriefrecord",
            index=models.Index(fields=["company", "operation"], name="op_briefs_company_op_idx"),
        ),
        migrations.AddConstraint(
            model_name="operatingbriefrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(operation__isnull=True),
                fields=("organization", "company"),
                name="operating_briefs_company_current_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="operatingbriefrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(operation__isnull=False),
                fields=("organization", "company", "operation"),
                name="operating_briefs_operation_current_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="interactioneventrecord",
            index=models.Index(fields=["organization", "created_at"], name="interaction_org_time_idx"),
        ),
        migrations.AddIndex(
            model_name="interactioneventrecord",
            index=models.Index(fields=["company", "created_at"], name="interaction_company_time_idx"),
        ),
        migrations.AddIndex(
            model_name="interactioneventrecord",
            index=models.Index(fields=["operation", "created_at"], name="interaction_operation_time_idx"),
        ),
        migrations.AddIndex(
            model_name="interactioneventrecord",
            index=models.Index(fields=["brief", "sequence"], name="interaction_brief_seq_idx"),
        ),
        migrations.AddConstraint(
            model_name="interactioneventrecord",
            constraint=models.UniqueConstraint(
                fields=("brief", "sequence"),
                name="interaction_events_brief_sequence_uniq",
            ),
        ),
    ]
