# Generated by Django 4.2.3 on 2026-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0054_company_archive_learning'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencelink',
            name='usage_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='evidencelink',
            index=models.Index(fields=['company', 'usage_key'], name='evid_comp_usage_idx'),
        ),
        migrations.AddConstraint(
            model_name='evidencelink',
            constraint=models.UniqueConstraint(condition=models.Q(('usage_key__gt', '')), fields=('company', 'usage_key'), name='evid_company_usage_key_uniq'),
        ),
        migrations.AddConstraint(
            model_name='preferenceevent',
            constraint=models.UniqueConstraint(condition=models.Q(('approval_task__isnull', False)), fields=('approval_task',), name='pref_approval_task_uniq'),
        ),
    ]
