# Generated by Codex on 2026-05-03

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0058_service_metric_samples"),
    ]

    operations = [
        migrations.CreateModel(
            name="StateFeedEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.CharField(max_length=128)),
                ("state_version", models.PositiveBigIntegerField()),
                ("type", models.CharField(max_length=96)),
                ("level", models.CharField(blank=True, default="", max_length=16)),
                ("requires_refetch", models.BooleanField(default=False)),
                ("message", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_feed_events",
                        to="orm.organization",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_feed_events",
                        to="orm.run",
                    ),
                ),
            ],
            options={
                "db_table": "state_feed_events",
                "ordering": ["state_version"],
            },
        ),
        migrations.AddConstraint(
            model_name="statefeedevent",
            constraint=models.UniqueConstraint(
                fields=("run", "state_version"),
                name="state_feed_run_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="statefeedevent",
            constraint=models.UniqueConstraint(
                fields=("run", "event_id"),
                name="state_feed_run_event_id_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="statefeedevent",
            index=models.Index(
                fields=["organization", "run", "state_version"],
                name="state_feed_org_run_ver_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="statefeedevent",
            index=models.Index(fields=["run", "created_at"], name="state_feed_run_created_idx"),
        ),
        migrations.AddIndex(
            model_name="statefeedevent",
            index=models.Index(
                fields=["organization", "created_at"],
                name="state_feed_org_created_idx",
            ),
        ),
    ]
