# Generated by Codex on 2026-05-03

from __future__ import annotations

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0059_state_feed_events"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDeadLetterRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.CharField(blank=True, default="", max_length=128)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=255)),
                ("event_type", models.CharField(blank=True, default="", max_length=96)),
                ("source", models.CharField(default="engine_callback", max_length=64)),
                ("reason", models.TextField()),
                ("error_class", models.CharField(blank=True, default="", max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("retry_count", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("acknowledged", "Acknowledged"),
                            ("replay_requested", "Replay Requested"),
                            ("resolved", "Resolved"),
                        ],
                        default="active",
                        max_length=32,
                    ),
                ),
                ("last_replay_action", models.TextField(blank=True, default="")),
                ("replay_requested_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledgement_reason", models.TextField(blank=True, default="")),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_event_dead_letters",
                        to="orm.user",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dead_letters",
                        to="orm.organization",
                    ),
                ),
                (
                    "replay_requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="replay_requested_event_dead_letters",
                        to="orm.user",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_dead_letters",
                        to="orm.run",
                    ),
                ),
            ],
            options={
                "db_table": "event_dead_letter_records",
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.AddIndex(
            model_name="eventdeadletterrecord",
            index=models.Index(
                fields=["organization", "status", "last_seen_at"],
                name="event_dl_org_status_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="eventdeadletterrecord",
            index=models.Index(fields=["run", "status"], name="event_dl_run_status_idx"),
        ),
        migrations.AddIndex(
            model_name="eventdeadletterrecord",
            index=models.Index(fields=["event_id"], name="event_dl_event_id_idx"),
        ),
        migrations.AddIndex(
            model_name="eventdeadletterrecord",
            index=models.Index(fields=["source", "last_seen_at"], name="event_dl_source_time_idx"),
        ),
    ]
