# Generated by Codex on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0067_domain_event_global_sequence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("document", "Document"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("dataset", "Dataset"),
                    ("report", "Report"),
                    ("deliverable", "Deliverable"),
                    ("memo", "Memo"),
                    ("policy_source", "Policy Source"),
                ],
                max_length=32,
            ),
        ),
    ]
