# Generated by Codex on 2026-05-08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0068_asset_video_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaGenerationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "modality",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")], max_length=16
                    ),
                ),
                ("provider", models.CharField(default="google", max_length=32)),
                ("model", models.CharField(max_length=128)),
                ("prompt", models.TextField()),
                ("prompt_hash", models.CharField(max_length=64)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_operation_name",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("output_mime_type", models.CharField(blank=True, default="", max_length=128)),
                ("output_size_bytes", models.PositiveBigIntegerField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("request_json", models.JSONField(blank=True, default=dict)),
                ("response_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_generation_jobs",
                        to="orm.graph",
                    ),
                ),
                (
                    "credential",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_generation_jobs",
                        to="orm.apikey",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_generation_jobs",
                        to="orm.organization",
                    ),
                ),
                (
                    "output_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orm.asset",
                    ),
                ),
                (
                    "output_asset_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orm.assetversion",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="media_generation_jobs",
                        to="orm.user",
                    ),
                ),
            ],
            options={
                "db_table": "media_generation_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="mediagenerationjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("company", "idempotency_key"),
                name="media_job_company_idempotency_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="mediagenerationjob",
            index=models.Index(fields=["organization", "status"], name="media_job_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="mediagenerationjob",
            index=models.Index(fields=["company", "status"], name="media_job_company_status_idx"),
        ),
        migrations.AddIndex(
            model_name="mediagenerationjob",
            index=models.Index(
                fields=["provider_operation_name"], name="media_job_provider_op_idx"
            ),
        ),
    ]
