# Generated by Django 6.0.4 on 2026-05-08 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0069_media_generation_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('variant', models.CharField(blank=True, default='', max_length=255)),
                ('color', models.CharField(blank=True, default='', max_length=128)),
                ('photo_url', models.CharField(blank=True, default='', max_length=1024)),
                ('price_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_margin_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('anchor_model', models.BooleanField(default=False)),
                ('scarcity_tag', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_products', to='orm.organization')),
            ],
            options={
                'db_table': 'inventory_products',
                'ordering': ['model', 'sku'],
            },
        ),
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('released', 'Released'), ('converted', 'Converted')], default='active', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('buyer_alias', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(choices=[('manual', 'Manual'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('dm', 'DM'), ('storefront', 'Storefront'), ('other', 'Other')], default='manual', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_reservations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='orm.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='orm.inventoryproduct')),
            ],
            options={
                'db_table': 'inventory_reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryOrderShell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order_shells', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_order_shells', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_order_shells', to='orm.organization')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='orm.inventoryreservation')),
            ],
            options={
                'db_table': 'inventory_order_shells',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryStockUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unit_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('removed', 'Removed')], default='available', max_length=16)),
                ('source', models.CharField(blank=True, default='legacy_csv', max_length=64)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_units', to='orm.graph')),
                ('current_reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_units', to='orm.inventoryreservation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_stock_units', to='orm.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_units', to='orm.inventoryproduct')),
            ],
            options={
                'db_table': 'inventory_stock_units',
                'ordering': ['product', 'unit_number'],
            },
        ),
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('import', 'Import'), ('reserve', 'Reserve'), ('release', 'Release'), ('expire', 'Expire'), ('extend', 'Extend'), ('order_shell', 'Order Shell'), ('adjust', 'Adjust')], max_length=32)),
                ('quantity_delta', models.IntegerField(default=0)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='orm.organization')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='orm.inventoryordershell')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='orm.inventoryproduct')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='orm.inventoryreservation')),
                ('stock_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to='orm.inventorystockunit')),
            ],
            options={
                'db_table': 'inventory_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['organization', 'status'], name='inventory_prod_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['company', 'status'], name='inventory_prod_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryproduct',
            index=models.Index(fields=['company', 'anchor_model'], name='inventory_prod_anchor_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryproduct',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='inventory_product_company_sku_uniq'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['organization', 'status'], name='inventory_res_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['company', 'status'], name='inventory_res_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['company', 'expires_at'], name='inventory_res_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='inventory_res_company_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='inventoryordershell',
            index=models.Index(fields=['organization', 'status'], name='inventory_order_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryordershell',
            index=models.Index(fields=['company', 'status'], name='inventory_order_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryordershell',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='inventory_order_company_number_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventoryordershell',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='inventory_order_company_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='inventorystockunit',
            index=models.Index(fields=['organization', 'status'], name='inventory_stock_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockunit',
            index=models.Index(fields=['company', 'status'], name='inventory_stock_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockunit',
            index=models.Index(fields=['product', 'status'], name='inventory_stock_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystockunit',
            index=models.Index(fields=['current_reservation'], name='inventory_stock_res_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorystockunit',
            constraint=models.UniqueConstraint(fields=('product', 'unit_number'), name='inventory_stock_product_unit_uniq'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['organization', 'created_at'], name='inventory_event_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['company', 'created_at'], name='inventory_event_company_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['product', 'created_at'], name='inventory_event_product_time_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryevent',
            index=models.Index(fields=['reservation'], name='inventory_event_res_idx'),
        ),
    ]
