# Generated by Django 6.0.4 on 2026-05-08 04:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0070_inventory_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceCashLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('sale', 'Sale')], default='sale', max_length=32)),
                ('amount_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('occurred_at', models.DateTimeField()),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commerce_cash_ledger_entries',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CommercePayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='stripe', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('expired', 'Expired'), ('failed', 'Failed'), ('review_required', 'Review Required')], default='pending', max_length=32)),
                ('amount_mxn', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('checkout_url', models.CharField(blank=True, default='', max_length=2048)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('latest_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('processed_event_ids', models.JSONField(blank=True, default=list)),
                ('customer_email', models.CharField(blank=True, default='', max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('shipping_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commerce_payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceStripeEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], max_length=16)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.CharField(blank=True, default='', max_length=1000)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commerce_stripe_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='customer_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='payment_expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='shipping_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='stripe_checkout_url',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='stripe_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('google', 'Google AI'), ('gmail', 'Gmail'), ('google_calendar', 'Google Calendar'), ('google_tasks', 'Google Tasks'), ('notion', 'Notion'), ('slack', 'Slack'), ('jira', 'Jira'), ('linear', 'Linear'), ('hubspot', 'HubSpot'), ('google_drive', 'Google Drive'), ('telegram', 'Telegram'), ('twilio', 'Twilio'), ('stripe', 'Stripe')], max_length=32),
        ),
        migrations.AlterField(
            model_name='inventoryordershell',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('payment_expired', 'Payment Expired'), ('cancelled', 'Cancelled'), ('payment_review_required', 'Payment Review Required')], default='pending_payment', max_length=32),
        ),
        migrations.AddIndex(
            model_name='inventoryordershell',
            index=models.Index(fields=['stripe_session_id'], name='inventory_order_stripe_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryordershell',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_session_id__gt', '')), fields=('stripe_session_id',), name='inventory_order_stripe_session_uniq'),
        ),
        migrations.AddField(
            model_name='commercecashledgerentry',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_cash_ledger_entries', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercecashledgerentry',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entries', to='orm.inventoryordershell'),
        ),
        migrations.AddField(
            model_name='commercecashledgerentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_cash_ledger_entries', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_payments', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payment', to='orm.inventoryordershell'),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_payments', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payments', to='orm.inventoryproduct'),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercepayment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_payments', to='orm.inventoryreservation'),
        ),
        migrations.AddField(
            model_name='commercecashledgerentry',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_ledger_entry', to='orm.commercepayment'),
        ),
        migrations.AddField(
            model_name='commercestripeevent',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_stripe_events', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercestripeevent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_stripe_events', to='orm.organization'),
        ),
        migrations.AddIndex(
            model_name='commercepayment',
            index=models.Index(fields=['organization', 'status'], name='commerce_payment_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commercepayment',
            index=models.Index(fields=['company', 'status'], name='commerce_payment_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commercepayment',
            index=models.Index(fields=['stripe_session_id'], name='commerce_payment_stripe_session_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='commerce_payment_company_idem_uniq'),
        ),
        migrations.AddConstraint(
            model_name='commercepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_session_id__gt', '')), fields=('stripe_session_id',), name='commerce_payment_stripe_session_uniq'),
        ),
        migrations.AddIndex(
            model_name='commercecashledgerentry',
            index=models.Index(fields=['organization', 'occurred_at'], name='commerce_cash_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='commercecashledgerentry',
            index=models.Index(fields=['company', 'occurred_at'], name='commerce_cash_company_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='commercecashledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='commerce_cash_company_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='commercestripeevent',
            index=models.Index(fields=['stripe_event_id'], name='commerce_stripe_event_id_idx'),
        ),
        migrations.AddIndex(
            model_name='commercestripeevent',
            index=models.Index(fields=['company', 'event_type'], name='commerce_stripe_company_type_idx'),
        ),
    ]
