# Generated by Django 6.0.4 on 2026-05-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0071_commerce_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryevent',
            name='event_type',
            field=models.CharField(choices=[('import', 'Import'), ('reserve', 'Reserve'), ('release', 'Release'), ('expire', 'Expire'), ('extend', 'Extend'), ('order_shell', 'Order Shell'), ('sell', 'Sell'), ('payment_expire', 'Payment Expire'), ('payment_review', 'Payment Review'), ('adjust', 'Adjust')], max_length=32),
        ),
    ]
