# Generated by Django 4.2.3 on 2026-05-08 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def backfill_canonical_commerce_fields(apps, schema_editor):
    InventoryProduct = apps.get_model("orm", "InventoryProduct")
    InventoryOrderShell = apps.get_model("orm", "InventoryOrderShell")

    for product in InventoryProduct.objects.all().iterator():
        updates = []
        if not product.price_amount:
            product.price_amount = product.price_mxn
            updates.append("price_amount")
        if not product.cost_amount:
            product.cost_amount = product.cost_mxn
            updates.append("cost_amount")
        if not product.currency:
            product.currency = "mxn"
            updates.append("currency")
        if updates:
            product.save(update_fields=updates)

    counts_by_company = {}
    for order in InventoryOrderShell.objects.order_by("company_id", "created_at", "id").iterator():
        updates = []
        company_key = str(order.company_id)
        counts_by_company[company_key] = counts_by_company.get(company_key, 0) + 1
        if not order.public_reference:
            order.public_reference = f"ORDER-{company_key[:6].upper()}-{counts_by_company[company_key]:05d}"
            updates.append("public_reference")
        if not order.public_status_token:
            order.public_status_token = uuid.uuid4().hex + uuid.uuid4().hex
            updates.append("public_status_token")
        if updates:
            order.save(update_fields=updates)


def noop_reverse(apps, schema_editor):
    _ = apps, schema_editor


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0072_commerce_checkout_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceFulfillment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=32)),
                ('reason_code', models.CharField(blank=True, default='', max_length=64)),
                ('operator_note', models.TextField(blank=True, default='')),
                ('carrier', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=120)),
                ('tracking_url', models.CharField(blank=True, default='', max_length=1024)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commerce_fulfillments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceFulfillmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Created'), ('ready', 'Ready'), ('blocked', 'Blocked'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('note', 'Note')], max_length=32)),
                ('status_from', models.CharField(blank=True, default='', max_length=32)),
                ('status_to', models.CharField(blank=True, default='', max_length=32)),
                ('message', models.CharField(blank=True, default='', max_length=512)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'commerce_fulfillment_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceStorefrontProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('success_path', models.CharField(blank=True, default='', max_length=255)),
                ('cancel_path', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'commerce_storefront_profiles',
                'ordering': ['slug'],
            },
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='comm_pay_org_status_idx',
            old_name='commerce_payment_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='comm_pay_company_status_idx',
            old_name='commerce_payment_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='commercepayment',
            new_name='comm_pay_stripe_sess_idx',
            old_name='commerce_payment_stripe_session_idx',
        ),
        migrations.RenameIndex(
            model_name='commercestripeevent',
            new_name='comm_stripe_company_type_idx',
            old_name='commerce_stripe_company_type_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryevent',
            new_name='inv_event_company_time_idx',
            old_name='inventory_event_company_time_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryevent',
            new_name='inv_event_product_time_idx',
            old_name='inventory_event_product_time_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryordershell',
            new_name='inv_order_company_status_idx',
            old_name='inventory_order_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryordershell',
            new_name='inv_order_stripe_sess_idx',
            old_name='inventory_order_stripe_session_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryproduct',
            new_name='inv_prod_company_status_idx',
            old_name='inventory_prod_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventoryreservation',
            new_name='inv_res_company_status_idx',
            old_name='inventory_res_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystockunit',
            new_name='inv_stock_company_status_idx',
            old_name='inventory_stock_company_status_idx',
        ),
        migrations.RenameIndex(
            model_name='inventorystockunit',
            new_name='inv_stock_product_status_idx',
            old_name='inventory_stock_product_status_idx',
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='public_reference',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='inventoryordershell',
            name='public_status_token',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='cost_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='currency',
            field=models.CharField(default='mxn', max_length=8),
        ),
        migrations.AddField(
            model_name='inventoryproduct',
            name='price_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(backfill_canonical_commerce_fields, noop_reverse),
        migrations.AlterField(
            model_name='inventorystockunit',
            name='source',
            field=models.CharField(blank=True, default='csv_import', max_length=64),
        ),
        migrations.AddIndex(
            model_name='inventoryordershell',
            index=models.Index(fields=['public_status_token'], name='inv_order_public_token_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventoryordershell',
            constraint=models.UniqueConstraint(condition=models.Q(('public_reference__gt', '')), fields=('company', 'public_reference'), name='inventory_order_public_ref_uniq'),
        ),
        migrations.AddConstraint(
            model_name='inventoryordershell',
            constraint=models.UniqueConstraint(condition=models.Q(('public_status_token__gt', '')), fields=('public_status_token',), name='inventory_order_public_token_uniq'),
        ),
        migrations.AddField(
            model_name='commercestorefrontprofile',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_storefront_profile', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercestorefrontprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_storefront_profiles', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='commercestorefrontprofile',
            name='stripe_credential',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_storefront_profiles', to='orm.apikey'),
        ),
        migrations.AddField(
            model_name='commercefulfillmentevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_fulfillment_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commercefulfillmentevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_fulfillment_events', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercefulfillmentevent',
            name='fulfillment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='orm.commercefulfillment'),
        ),
        migrations.AddField(
            model_name='commercefulfillmentevent',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillment_events', to='orm.inventoryordershell'),
        ),
        migrations.AddField(
            model_name='commercefulfillmentevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_fulfillment_events', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='commercefulfillment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_fulfillments', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='commercefulfillment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_fulfillment', to='orm.inventoryordershell'),
        ),
        migrations.AddField(
            model_name='commercefulfillment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_fulfillments', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='commercefulfillment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_fulfillment', to='orm.commercepayment'),
        ),
        migrations.AddField(
            model_name='commercefulfillment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commerce_fulfillments', to='orm.inventoryreservation'),
        ),
        migrations.AddIndex(
            model_name='commercestorefrontprofile',
            index=models.Index(fields=['organization', 'enabled'], name='storefront_org_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='commercestorefrontprofile',
            index=models.Index(fields=['company', 'enabled'], name='storefront_company_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='commercestorefrontprofile',
            index=models.Index(fields=['slug', 'enabled'], name='storefront_slug_enabled_idx'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillmentevent',
            index=models.Index(fields=['organization', 'created_at'], name='commerce_fevent_org_time_idx'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillmentevent',
            index=models.Index(fields=['company', 'created_at'], name='comm_fevent_company_time'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillmentevent',
            index=models.Index(fields=['fulfillment', 'created_at'], name='commerce_fevent_fulfill_idx'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillment',
            index=models.Index(fields=['organization', 'status'], name='comm_fulfill_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillment',
            index=models.Index(fields=['company', 'status'], name='comm_fulfill_company_status'),
        ),
        migrations.AddIndex(
            model_name='commercefulfillment',
            index=models.Index(fields=['company', 'updated_at'], name='comm_fulfill_company_time'),
        ),
    ]
