# Generated by Django 4.2.3 on 2026-05-08 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0073_commerce_control_tower'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommerceProcurementDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True, default='')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_procurement_drafts', to='orm.approvaltask')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurement_drafts', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_procurement_drafts', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commerce_procurement_drafts', to='orm.organization')),
                ('origin_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commerce_procurement_drafts', to='orm.run')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_procurement_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'commerce_procurement_drafts',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signal_type', models.CharField(choices=[('demand', 'Demand'), ('lead', 'Lead'), ('stockout', 'Stockout'), ('content_response', 'Content Response'), ('fulfillment_issue', 'Fulfillment Issue'), ('paid_order', 'Paid Order'), ('manual', 'Manual')], max_length=32)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('dismissed', 'Dismissed')], default='new', max_length=16)),
                ('source', models.CharField(blank=True, default='manual', max_length=64)),
                ('external_key', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('contact_alias', models.CharField(blank=True, default='', max_length=120)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_signals', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signals', to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signals', to='orm.commercefulfillment')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signals', to='orm.run')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signals', to='orm.inventoryordershell')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_signals', to='orm.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_signals', to='orm.inventoryproduct')),
            ],
            options={
                'db_table': 'company_signals',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('follow_up', 'Follow Up'), ('reserved', 'Reserved'), ('converted', 'Converted'), ('lost', 'Lost')], default='qualified', max_length=32)),
                ('external_key', models.CharField(blank=True, default='', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('contact_alias', models.CharField(blank=True, default='', max_length=120)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('estimated_value_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('next_action', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_opportunities', to='orm.graph')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_opportunities', to='orm.inventoryordershell')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_opportunities', to='orm.organization')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_opportunities', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_opportunities', to='orm.inventoryproduct')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_opportunities', to='orm.inventoryreservation')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='orm.companysignal')),
            ],
            options={
                'db_table': 'company_opportunities',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommerceProcurementDraftLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, default='', max_length=128)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='mxn', max_length=8)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='orm.commerceprocurementdraft')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_draft_lines', to='orm.inventoryproduct')),
            ],
            options={
                'db_table': 'commerce_procurement_draft_lines',
                'ordering': ['draft', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('audience', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('call_to_action', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approval_requested', 'Approval Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('published', 'Published'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.approvaltask')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_publication_drafts', to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.asset')),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.assetversion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_drafts', to='orm.graph')),
                ('media_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.mediagenerationjob')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.companyopportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_drafts', to='orm.organization')),
                ('origin_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.run')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_publication_drafts', to=settings.AUTH_USER_MODEL)),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication_drafts', to='orm.companysignal')),
            ],
            options={
                'db_table': 'publication_drafts',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='pub_draft_org_status_idx'), models.Index(fields=['company', 'status'], name='pub_draft_company_status_idx'), models.Index(fields=['company', 'updated_at'], name='pub_draft_updated_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='publicationdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='publication_draft_company_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='companysignal',
            index=models.Index(fields=['organization', 'status'], name='company_signal_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignal',
            index=models.Index(fields=['company', 'signal_type'], name='company_signal_type_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignal',
            index=models.Index(fields=['company', 'status'], name='company_signal_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companysignal',
            index=models.Index(fields=['company', 'occurred_at'], name='company_signal_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='companysignal',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__gt', '')), fields=('company', 'source', 'external_key'), name='company_signal_source_ext_uniq'),
        ),
        migrations.AddIndex(
            model_name='companyopportunity',
            index=models.Index(fields=['organization', 'status'], name='company_opp_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyopportunity',
            index=models.Index(fields=['company', 'status'], name='company_opp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyopportunity',
            index=models.Index(fields=['company', 'updated_at'], name='company_opp_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyopportunity',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__gt', '')), fields=('company', 'external_key'), name='company_opp_external_uniq'),
        ),
        migrations.AddIndex(
            model_name='commerceprocurementdraftline',
            index=models.Index(fields=['draft'], name='proc_line_draft_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceprocurementdraftline',
            index=models.Index(fields=['product'], name='proc_line_product_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceprocurementdraft',
            index=models.Index(fields=['organization', 'status'], name='proc_draft_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceprocurementdraft',
            index=models.Index(fields=['company', 'status'], name='proc_draft_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='commerceprocurementdraft',
            index=models.Index(fields=['company', 'updated_at'], name='proc_draft_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='commerceprocurementdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('company', 'idempotency_key'), name='procurement_draft_company_idem_uniq'),
        ),
    ]
