# Generated by Django 4.2.3 on 2026-05-08 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0074_company_operating_loop'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyOperationObjective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('rehearsal', 'Rehearsal'), ('demand', 'Demand'), ('commerce', 'Commerce'), ('live_selling', 'Live Selling')], default='rehearsal', max_length=32)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('evaluated', 'Evaluated')], default='planned', max_length=16)),
                ('run_goal', models.TextField()),
                ('hypothesis', models.TextField(blank=True, default='')),
                ('target_signal', models.TextField(blank=True, default='')),
                ('action_plan_json', models.JSONField(blank=True, default=list)),
                ('integrity_gates_json', models.JSONField(blank=True, default=dict)),
                ('success_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('miss_analysis', models.TextField(blank=True, default='')),
                ('next_decision', models.TextField(blank=True, default='')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_operation_objectives', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_operation_objectives', to=settings.AUTH_USER_MODEL)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_objective', to='orm.run')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_operation_objectives', to='orm.organization')),
                ('source_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_objectives', to='orm.companysignal')),
            ],
            options={
                'db_table': 'company_operation_objectives',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company', 'status'], name='company_obj_status_idx'), models.Index(fields=['company', 'run_type'], name='company_obj_run_type_idx'), models.Index(fields=['organization', 'created_at'], name='company_obj_org_time_idx')],
            },
        ),
    ]
