# Generated by Django 4.2.3 on 2026-05-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0075_companyoperationobjective'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisionrecord',
            name='decision_type',
            field=models.CharField(choices=[('human_approval', 'Human Approval'), ('policy_guardrail', 'Policy Guardrail'), ('marketplace_review', 'Marketplace Review'), ('operator_intervention', 'Operator Intervention'), ('objective_evaluation', 'Objective Evaluation')], max_length=32),
        ),
    ]
