# Generated by Codex on 2026-05-08

from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0076_alter_decisionrecord_decision_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskJudge",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("source_node_id", models.CharField(blank=True, default="", max_length=255)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("instructions", models.TextField(blank=True, default="")),
                ("criteria_json", models.JSONField(blank=True, default=list)),
                (
                    "pass_threshold",
                    models.PositiveSmallIntegerField(
                        default=80,
                        validators=[MinValueValidator(1), MaxValueValidator(100)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("inconclusive", "Inconclusive"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[MinValueValidator(0), MaxValueValidator(100)],
                    ),
                ),
                ("result_json", models.JSONField(blank=True, default=dict)),
                ("evaluated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_task_judges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "execution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_judges",
                        to="orm.run",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_judges",
                        to="orm.organization",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="judge",
                        to="orm.taskrecord",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_task_judges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "task_judges",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="taskjudge",
            index=models.Index(fields=["organization", "status"], name="task_judges_org_status_idx"),
        ),
        migrations.AddIndex(
            model_name="taskjudge",
            index=models.Index(fields=["execution", "source_node_id"], name="task_judges_exec_node_idx"),
        ),
        migrations.AddIndex(
            model_name="taskjudge",
            index=models.Index(fields=["evaluated_at"], name="task_judges_eval_time_idx"),
        ),
    ]
