# Generated by Django 4.2.3 on 2026-05-11 23:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0078_openrouter_api_key_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssertionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('FACT', 'Fact'), ('OPINION', 'Opinion'), ('ASSUMPTION', 'Assumption'), ('QUESTION', 'Question')], max_length=16)),
                ('pack_label', models.CharField(blank=True, default='', max_length=80)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('statement', models.TextField()),
                ('source', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('validation_status', models.CharField(choices=[('unvalidated', 'Unvalidated'), ('pending', 'Pending'), ('validated', 'Validated'), ('rejected', 'Rejected'), ('corrected', 'Corrected'), ('client_asserted', 'Client Asserted'), ('open', 'Open')], default='unvalidated', max_length=32)),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'assertion_records',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDependency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dependency_type', models.CharField(choices=[('derived_from', 'Derived From'), ('cites', 'Cites'), ('supersedes', 'Supersedes'), ('requires', 'Requires'), ('informs', 'Informs')], default='derived_from', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_dependencies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapacityPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('plan_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'capacity_plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyOperatingModelInstallation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('removed', 'Removed'), ('upgrade_available', 'Upgrade Available')], default='active', max_length=32)),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('dashboard_json', models.JSONField(blank=True, default=dict)),
                ('install_metadata_json', models.JSONField(blank=True, default=dict)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company_operating_model_installations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(blank=True, default='', max_length=160)),
                ('template_id', models.CharField(max_length=160)),
                ('display_label', models.CharField(default='Program', max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('current_stage_id', models.CharField(blank=True, default='', max_length=120)),
                ('external_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_programs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTeamAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment_scope', models.CharField(default='company', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('capacity_weight', models.FloatField(default=1)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_team_assignments',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTeamRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_key', models.CharField(max_length=120)),
                ('display_label', models.CharField(max_length=160)),
                ('permissions_json', models.JSONField(blank=True, default=list)),
                ('approval_level', models.CharField(blank=True, default='', max_length=32)),
                ('capacity_per_week', models.PositiveSmallIntegerField(default=0)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_team_roles',
                'ordering': ['display_label'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], max_length=16)),
                ('issue_type', models.CharField(max_length=120)),
                ('message', models.TextField()),
                ('evidence_refs_json', models.JSONField(blank=True, default=list)),
                ('suggested_fix', models.TextField(blank=True, default='')),
                ('blocking', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluation_findings',
                'ordering': ['-blocking', 'severity', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=255)),
                ('mode', models.CharField(blank=True, default='', max_length=80)),
                ('rubric_json', models.JSONField(blank=True, default=dict)),
                ('weights_json', models.JSONField(blank=True, default=dict)),
                ('thresholds_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'evaluation_profiles',
                'ordering': ['profile_id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_key', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('PASS', 'Pass'), ('WARN', 'Warn'), ('BLOCK', 'Block'), ('RUNNING', 'Running'), ('FAILED', 'Failed')], default='RUNNING', max_length=16)),
                ('score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, default='', max_length=8)),
                ('input_refs_json', models.JSONField(blank=True, default=list)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'evaluation_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationScorecard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dimensions_json', models.JSONField(blank=True, default=dict)),
                ('composite_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, default='', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluation_scorecards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OperatingModelPackRelease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(max_length=160)),
                ('base_pack_id', models.CharField(max_length=120)),
                ('version', models.CharField(max_length=32)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('checksum', models.CharField(max_length=64)),
                ('manifest_json', models.JSONField(blank=True, default=dict)),
                ('files_json', models.JSONField(blank=True, default=dict)),
                ('compatibility_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('disabled', 'Disabled')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'operating_model_pack_releases',
                'ordering': ['base_pack_id', '-version'],
            },
        ),
        migrations.CreateModel(
            name='ReworkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approval_required', 'Approval Required'), ('approved', 'Approved'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('trigger_summary', models.TextField(blank=True, default='')),
                ('impact_json', models.JSONField(blank=True, default=dict)),
                ('required_approvals_json', models.JSONField(blank=True, default=list)),
                ('estimated_effort_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_plans', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rework_plans', to=settings.AUTH_USER_MODEL)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_rework_plans', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_plans', to='orm.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_plans', to='orm.companyprogram')),
            ],
            options={
                'db_table': 'rework_plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidationDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accept'), ('REJECT', 'Reject'), ('EDIT', 'Edit'), ('DEFER', 'Defer'), ('NEEDS_RESEARCH', 'Needs Research')], max_length=32)),
                ('category', models.CharField(blank=True, default='', max_length=120)),
                ('rationale', models.TextField(blank=True, default='')),
                ('proposed_change_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assertion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_decisions', to='orm.assertionrecord')),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_decisions', to='orm.asset')),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_decisions', to='orm.assetversion')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_decisions', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_validation_decisions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_decisions', to='orm.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_decisions', to='orm.companyprogram')),
            ],
            options={
                'db_table': 'validation_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StateProjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projection_type', models.CharField(max_length=120)),
                ('display_label', models.CharField(default='Current State', max_length=160)),
                ('source_refs_json', models.JSONField(blank=True, default=list)),
                ('json_state', models.JSONField(blank=True, default=dict)),
                ('markdown_summary', models.TextField(blank=True, default='')),
                ('generated_by', models.CharField(default='system', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_projections', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_projections', to='orm.organization')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='state_projections', to='orm.companyprogram')),
            ],
            options={
                'db_table': 'state_projections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalTaxonomy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('taxonomy_id', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=255)),
                ('definitions_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_taxonomies', to='orm.graph')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signal_taxonomies', to='orm.organization')),
                ('pack_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal_taxonomies', to='orm.operatingmodelpackrelease')),
            ],
            options={
                'db_table': 'signal_taxonomies',
                'ordering': ['taxonomy_id'],
            },
        ),
        migrations.CreateModel(
            name='ReworkPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=64)),
                ('target_id', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=120)),
                ('reason', models.TextField(blank=True, default='')),
                ('recommended_order', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('skipped', 'Skipped'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_plan_items', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rework_plan_items', to='orm.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orm.reworkplan')),
            ],
            options={
                'db_table': 'rework_plan_items',
                'ordering': ['plan', 'recommended_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgramStageState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=255)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('active', 'Active'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=16)),
                ('state_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_stage_states', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_stage_states', to='orm.organization')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_states', to='orm.companyprogram')),
            ],
            options={
                'db_table': 'program_stage_states',
                'ordering': ['program', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pack_id', models.CharField(blank=True, default='', max_length=160)),
                ('score', models.FloatField(blank=True, null=True)),
                ('summary_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_health_snapshots', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_portfolio_health_snapshots', to=settings.AUTH_USER_MODEL)),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolio_health_snapshots', to='orm.companyoperatingmodelinstallation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_health_snapshots', to='orm.organization')),
            ],
            options={
                'db_table': 'portfolio_health_snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyPack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_pack_id', models.CharField(max_length=160)),
                ('display_name', models.CharField(max_length=255)),
                ('rules_json', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('deprecated', 'Deprecated')], default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_packs', to='orm.graph')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy_packs', to='orm.organization')),
                ('pack_release', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_packs', to='orm.operatingmodelpackrelease')),
            ],
            options={
                'db_table': 'policy_packs',
                'ordering': ['policy_pack_id'],
            },
        ),
        migrations.CreateModel(
            name='PolicyEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=120)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=16)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('approval_required', 'Approval Required'), ('blocked', 'Blocked')], default='allowed', max_length=32)),
                ('input_json', models.JSONField(blank=True, default=dict)),
                ('trace_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluations', to='orm.approvaltask')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_evaluations', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policy_evaluations', to=settings.AUTH_USER_MODEL)),
                ('decision_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluations', to='orm.decisionrecord')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_evaluations', to='orm.organization')),
                ('policy_pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_evaluations', to='orm.policypack')),
            ],
            options={
                'db_table': 'policy_evaluations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='operatingmodelpackrelease',
            index=models.Index(fields=['base_pack_id', 'status'], name='op_pack_base_status_idx'),
        ),
        migrations.AddIndex(
            model_name='operatingmodelpackrelease',
            index=models.Index(fields=['status', 'updated_at'], name='op_pack_status_updated_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatingmodelpackrelease',
            constraint=models.UniqueConstraint(fields=('pack_id',), name='op_model_pack_release_pack_id_uniq'),
        ),
        migrations.AddField(
            model_name='evaluationscorecard',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scorecards', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='evaluationscorecard',
            name='evaluation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='orm.evaluationrun'),
        ),
        migrations.AddField(
            model_name='evaluationscorecard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_scorecards', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='orm.asset'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='orm.assetversion'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_evaluation_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='orm.run'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_runs', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='orm.evaluationprofile'),
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='orm.companyprogram'),
        ),
        migrations.AddField(
            model_name='evaluationprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_profiles', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='evaluationprofile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_profiles', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='evaluationprofile',
            name='pack_release',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_profiles', to='orm.operatingmodelpackrelease'),
        ),
        migrations.AddField(
            model_name='evaluationfinding',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_findings', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='evaluationfinding',
            name='evaluation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='orm.evaluationrun'),
        ),
        migrations.AddField(
            model_name='evaluationfinding',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_findings', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='companyteamrole',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_team_roles', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='companyteamrole',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_team_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyteamrole',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_roles', to='orm.companyoperatingmodelinstallation'),
        ),
        migrations.AddField(
            model_name='companyteamrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_team_roles', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='companyteamassignment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_team_assignments', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='companyteamassignment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_team_assignments', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='companyteamassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_assignments', to='orm.companyprogram'),
        ),
        migrations.AddField(
            model_name='companyteamassignment',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='orm.companyteamrole'),
        ),
        migrations.AddField(
            model_name='companyteamassignment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_team_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_programs', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company_programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='orm.companyoperatingmodelinstallation'),
        ),
        migrations.AddField(
            model_name='companyprogram',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_programs', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='companyoperatingmodelinstallation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_model_installations', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='companyoperatingmodelinstallation',
            name='installed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_model_installations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyoperatingmodelinstallation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_model_installations', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='companyoperatingmodelinstallation',
            name='pack_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='company_installations', to='orm.operatingmodelpackrelease'),
        ),
        migrations.AddField(
            model_name='capacityplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_plans', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='capacityplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capacity_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='capacityplan',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capacity_plans', to='orm.companyoperatingmodelinstallation'),
        ),
        migrations.AddField(
            model_name='capacityplan',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacity_plans', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_dependencies', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_dependencies', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='source_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_dependencies', to='orm.asset'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='source_asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_dependencies', to='orm.assetversion'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='target_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_dependencies', to='orm.asset'),
        ),
        migrations.AddField(
            model_name='assetdependency',
            name='target_asset_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_dependencies', to='orm.assetversion'),
        ),
        migrations.AddField(
            model_name='assertionrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertion_records', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='assertionrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assertion_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assertionrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertion_records', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='assertionrecord',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assertion_records', to='orm.companyprogram'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['company', 'decision'], name='validation_company_dec_idx'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['program', 'category'], name='validation_program_cat_idx'),
        ),
        migrations.AddIndex(
            model_name='validationdecision',
            index=models.Index(fields=['asset'], name='validation_asset_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprojection',
            index=models.Index(fields=['company', 'projection_type'], name='state_proj_company_type_idx'),
        ),
        migrations.AddIndex(
            model_name='stateprojection',
            index=models.Index(fields=['program', 'projection_type'], name='state_proj_program_type_idx'),
        ),
        migrations.AddConstraint(
            model_name='stateprojection',
            constraint=models.UniqueConstraint(condition=models.Q(('program__isnull', False)), fields=('company', 'program', 'projection_type'), name='state_projection_program_type_uniq'),
        ),
        migrations.AddConstraint(
            model_name='stateprojection',
            constraint=models.UniqueConstraint(condition=models.Q(('program__isnull', True)), fields=('company', 'projection_type'), name='state_projection_company_type_uniq'),
        ),
        migrations.AddIndex(
            model_name='signaltaxonomy',
            index=models.Index(fields=['organization', 'status'], name='signal_tax_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='signaltaxonomy',
            index=models.Index(fields=['company', 'status'], name='signal_tax_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkplanitem',
            index=models.Index(fields=['plan', 'status'], name='rework_item_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkplanitem',
            index=models.Index(fields=['company', 'item_type'], name='rework_item_company_type_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkplan',
            index=models.Index(fields=['company', 'status'], name='rework_plan_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reworkplan',
            index=models.Index(fields=['program', 'status'], name='rework_plan_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='programstagestate',
            index=models.Index(fields=['company', 'status'], name='stage_state_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='programstagestate',
            index=models.Index(fields=['program', 'status'], name='stage_state_program_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='programstagestate',
            constraint=models.UniqueConstraint(fields=('program', 'stage_id'), name='program_stage_state_program_stage_uniq'),
        ),
        migrations.AddIndex(
            model_name='portfoliohealthsnapshot',
            index=models.Index(fields=['organization', 'pack_id'], name='portfolio_org_pack_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliohealthsnapshot',
            index=models.Index(fields=['company', 'created_at'], name='portfolio_company_time_idx'),
        ),
        migrations.AddIndex(
            model_name='policypack',
            index=models.Index(fields=['organization', 'status'], name='policy_pack_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policypack',
            index=models.Index(fields=['company', 'status'], name='policy_pack_company_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='policypack',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'policy_pack_id'), name='policy_pack_company_pack_uniq'),
        ),
        migrations.AddConstraint(
            model_name='policypack',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('pack_release__isnull', False)), fields=('pack_release', 'policy_pack_id'), name='policy_pack_release_pack_uniq'),
        ),
        migrations.AddIndex(
            model_name='policyevaluation',
            index=models.Index(fields=['company', 'status'], name='policy_eval_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='policyevaluation',
            index=models.Index(fields=['company', 'risk_level'], name='policy_eval_company_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='policyevaluation',
            index=models.Index(fields=['action_type', 'risk_level'], name='policy_eval_action_risk_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationscorecard',
            index=models.Index(fields=['company', 'created_at'], name='eval_score_company_time_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['company', 'status'], name='eval_run_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['asset', 'created_at'], name='eval_run_asset_time_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['program', 'created_at'], name='eval_run_program_time_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationrun',
            index=models.Index(fields=['profile_key', 'status'], name='eval_run_prof_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationprofile',
            index=models.Index(fields=['organization', 'status'], name='eval_profile_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationprofile',
            index=models.Index(fields=['company', 'status'], name='eval_prof_comp_stat_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'profile_id'), name='eval_profile_company_profile_uniq'),
        ),
        migrations.AddConstraint(
            model_name='evaluationprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', True), ('pack_release__isnull', False)), fields=('pack_release', 'profile_id'), name='eval_profile_pack_profile_uniq'),
        ),
        migrations.AddIndex(
            model_name='evaluationfinding',
            index=models.Index(fields=['evaluation', 'blocking'], name='eval_finding_eval_block_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluationfinding',
            index=models.Index(fields=['company', 'severity'], name='eval_finding_company_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='companyteamrole',
            index=models.Index(fields=['organization', 'role_key'], name='team_role_org_key_idx'),
        ),
        migrations.AddIndex(
            model_name='companyteamrole',
            index=models.Index(fields=['company', 'approval_level'], name='team_role_company_level_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyteamrole',
            constraint=models.UniqueConstraint(fields=('company', 'role_key'), name='company_team_role_company_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='companyteamassignment',
            index=models.Index(fields=['company', 'status'], name='team_assign_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyteamassignment',
            index=models.Index(fields=['role', 'status'], name='team_assign_role_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyteamassignment',
            index=models.Index(fields=['program', 'status'], name='team_assign_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprogram',
            index=models.Index(fields=['organization', 'status'], name='company_program_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprogram',
            index=models.Index(fields=['company', 'status'], name='company_program_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprogram',
            index=models.Index(fields=['company', 'pack_id'], name='company_program_pack_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprogram',
            index=models.Index(fields=['company', 'template_id'], name='company_program_template_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyprogram',
            constraint=models.UniqueConstraint(condition=models.Q(('external_key__gt', '')), fields=('company', 'external_key'), name='company_program_external_key_uniq'),
        ),
        migrations.AddIndex(
            model_name='companyoperatingmodelinstallation',
            index=models.Index(fields=['organization', 'status'], name='op_install_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyoperatingmodelinstallation',
            index=models.Index(fields=['company', 'status'], name='op_install_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='companyoperatingmodelinstallation',
            index=models.Index(fields=['pack_id', 'status'], name='op_install_pack_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='companyoperatingmodelinstallation',
            constraint=models.UniqueConstraint(fields=('company', 'pack_id'), name='company_op_model_install_company_pack_uniq'),
        ),
        migrations.AddIndex(
            model_name='capacityplan',
            index=models.Index(fields=['company', 'period_start'], name='capacity_company_start_idx'),
        ),
        migrations.AddIndex(
            model_name='capacityplan',
            index=models.Index(fields=['organization', 'period_start'], name='capacity_org_start_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdependency',
            index=models.Index(fields=['company', 'dependency_type'], name='asset_dep_company_type_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdependency',
            index=models.Index(fields=['source_asset'], name='asset_dep_source_idx'),
        ),
        migrations.AddIndex(
            model_name='assetdependency',
            index=models.Index(fields=['target_asset'], name='asset_dep_target_idx'),
        ),
        migrations.AddConstraint(
            model_name='assetdependency',
            constraint=models.UniqueConstraint(fields=('source_asset', 'source_asset_version', 'target_asset', 'target_asset_version', 'dependency_type'), name='asset_dependency_unique_edge'),
        ),
        migrations.AddIndex(
            model_name='assertionrecord',
            index=models.Index(fields=['organization', 'kind'], name='assertion_org_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='assertionrecord',
            index=models.Index(fields=['company', 'kind'], name='assertion_company_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='assertionrecord',
            index=models.Index(fields=['program', 'validation_status'], name='assert_program_val_idx'),
        ),
        migrations.AddIndex(
            model_name='assertionrecord',
            index=models.Index(fields=['company', 'validation_status'], name='assert_company_val_idx'),
        ),
    ]
