# Generated by Django 4.2.3 on 2026-05-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0079_assertionrecord_assetdependency_capacityplan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programstagestate",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_started", "Not Started"),
                    ("in_progress", "In Progress"),
                    ("blocked", "Blocked"),
                    ("awaiting_validation", "Awaiting Validation"),
                    ("completed", "Completed"),
                    ("rerun_required", "Rerun Required"),
                ],
                default="not_started",
                max_length=32,
            ),
        ),
    ]
