# Generated by Django 4.2.3 on 2026-05-12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0080_program_stage_lifecycle_statuses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicReviewDefinition",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pack_id", models.CharField(blank=True, default="", max_length=160)),
                ("template_id", models.CharField(max_length=160)),
                ("display_name", models.CharField(max_length=255)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("custom", "Custom"),
                        ],
                        default="monthly",
                        max_length=24,
                    ),
                ),
                ("timezone", models.CharField(blank=True, default="UTC", max_length=64)),
                ("evaluation_profile_key", models.CharField(blank=True, default="", max_length=160)),
                ("report_template_id", models.CharField(blank=True, default="", max_length=160)),
                ("history_projection_type", models.CharField(blank=True, default="", max_length=120)),
                ("enabled", models.BooleanField(default=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_review_definitions",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_periodic_review_definitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodic_review_definitions",
                        to="orm.evaluationprofile",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="periodic_review_definitions",
                        to="orm.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="periodic_review_definitions",
                        to="orm.companyprogram",
                    ),
                ),
            ],
            options={
                "db_table": "periodic_review_definitions",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="MetricSnapshot",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("metric_values_json", models.JSONField(blank=True, default=dict)),
                ("metric_sources_json", models.JSONField(blank=True, default=dict)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("connector", "Connector"),
                            ("manual", "Manual"),
                            ("imported", "Imported"),
                            ("computed", "Computed"),
                            ("seed", "Seed"),
                        ],
                        default="manual",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_metric_snapshots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_snapshots",
                        to="orm.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_snapshots",
                        to="orm.companyprogram",
                    ),
                ),
                (
                    "review_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="metric_snapshots",
                        to="orm.periodicreviewdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "metric_snapshots",
                "ordering": ["-period_start", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("report_template_id", models.CharField(blank=True, default="", max_length=160)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("evaluation_run_ids_json", models.JSONField(blank=True, default=list)),
                ("generated_sections_json", models.JSONField(blank=True, default=dict)),
                ("source_refs_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to="orm.asset",
                    ),
                ),
                (
                    "artifact_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to="orm.assetversion",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "metric_snapshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to="orm.metricsnapshot",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_runs",
                        to="orm.organization",
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to="orm.companyprogram",
                    ),
                ),
                (
                    "review_definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to="orm.periodicreviewdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "report_runs",
                "ordering": ["-period_start", "-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="periodicreviewdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("program__isnull", False)),
                fields=("company", "program", "template_id"),
                name="per_rev_comp_prog_tpl_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="periodicreviewdefinition",
            constraint=models.UniqueConstraint(
                condition=models.Q(("program__isnull", True)),
                fields=("company", "template_id"),
                name="per_rev_comp_tpl_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="periodicreviewdefinition",
            index=models.Index(fields=["organization", "enabled"], name="per_rev_org_en_idx"),
        ),
        migrations.AddIndex(
            model_name="periodicreviewdefinition",
            index=models.Index(fields=["company", "enabled"], name="per_rev_comp_en_idx"),
        ),
        migrations.AddIndex(
            model_name="periodicreviewdefinition",
            index=models.Index(fields=["company", "cadence"], name="per_rev_comp_cad_idx"),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(fields=["organization", "period_start"], name="metric_snap_org_period_idx"),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(fields=["company", "period_start"], name="metric_snap_comp_period_idx"),
        ),
        migrations.AddIndex(
            model_name="metricsnapshot",
            index=models.Index(fields=["review_definition", "period_start"], name="metric_snap_rev_period_idx"),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(fields=["organization", "period_start"], name="report_run_org_period_idx"),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(fields=["company", "period_start"], name="report_run_company_period_idx"),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(fields=["review_definition", "period_start"], name="report_run_review_period_idx"),
        ),
    ]
