# Generated by Codex on 2026-05-12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orm", "0081_periodic_reviews_metric_snapshots_report_runs"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyoperatingmodelinstallation",
            name="status",
            field=models.CharField(
                choices=[
                    ("installing", "Installing"),
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                    ("archived", "Archived"),
                    ("upgrading", "Upgrading"),
                    ("rollback_pending", "Rollback Pending"),
                    ("failed", "Failed"),
                    ("removed", "Removed"),
                    ("upgrade_available", "Upgrade Available"),
                ],
                default="active",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="active_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="base_pack_id",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="namespace",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="private_config_ref",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="public_config_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="companyoperatingmodelinstallation",
            name="role",
            field=models.CharField(
                choices=[("primary", "Primary"), ("addon", "Add-on")],
                default="addon",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="CompanyAccessPolicy",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("assignment_required", models.BooleanField(default=False)),
                ("org_admin_access_enabled", models.BooleanField(default=True)),
                ("cross_client_learning_enabled", models.BooleanField(default=False)),
                ("learning_policy_json", models.JSONField(blank=True, default=dict)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_policy",
                        to="orm.graph",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_access_policies",
                        to="orm.organization",
                    ),
                ),
            ],
            options={
                "db_table": "company_access_policies",
                "ordering": ["company_id"],
            },
        ),
        migrations.CreateModel(
            name="CompanyAssignment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "role",
                    models.CharField(
                        choices=[("viewer", "Viewer"), ("member", "Member"), ("admin", "Admin")],
                        default="viewer",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_company_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to="orm.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "company_assignments",
                "ordering": ["company", "user"],
            },
        ),
        migrations.CreateModel(
            name="PackInstallationConfigRevision",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("version", models.PositiveIntegerField()),
                ("public_config_json", models.JSONField(blank=True, default=dict)),
                ("private_config_ref", models.CharField(blank=True, default="", max_length=255)),
                ("change_reason", models.CharField(blank=True, default="", max_length=120)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_installation_config_revisions",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pack_config_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config_revisions",
                        to="orm.companyoperatingmodelinstallation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_installation_config_revisions",
                        to="orm.organization",
                    ),
                ),
            ],
            options={
                "db_table": "pack_installation_config_revisions",
                "ordering": ["installation", "-version"],
            },
        ),
        migrations.CreateModel(
            name="PackNamespaceClaim",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("pack_id", models.CharField(max_length=160)),
                ("object_type", models.CharField(max_length=80)),
                ("object_id", models.CharField(max_length=200)),
                ("namespaced_id", models.CharField(max_length=400)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("released", "Released"),
                            ("conflict", "Conflict"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("source_checksum", models.CharField(blank=True, default="", max_length=64)),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_namespace_claims",
                        to="orm.graph",
                    ),
                ),
                (
                    "installation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="namespace_claims",
                        to="orm.companyoperatingmodelinstallation",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pack_namespace_claims",
                        to="orm.organization",
                    ),
                ),
            ],
            options={
                "db_table": "pack_namespace_claims",
                "ordering": ["object_type", "namespaced_id"],
            },
        ),
        migrations.AddConstraint(
            model_name="companyoperatingmodelinstallation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "primary"), ("status", "active")),
                fields=("company", "role"),
                name="company_op_model_one_active_primary",
            ),
        ),
        migrations.AddIndex(
            model_name="companyoperatingmodelinstallation",
            index=models.Index(fields=["company", "role", "status"], name="op_install_company_role_idx"),
        ),
        migrations.AddIndex(
            model_name="companyaccesspolicy",
            index=models.Index(fields=["organization", "assignment_required"], name="company_access_org_req_idx"),
        ),
        migrations.AddConstraint(
            model_name="companyassignment",
            constraint=models.UniqueConstraint(
                fields=("company", "user"),
                name="company_assignment_company_user_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="companyassignment",
            index=models.Index(fields=["organization", "status"], name="comp_assign_org_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="companyassignment",
            index=models.Index(fields=["company", "status"], name="comp_assign_comp_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="companyassignment",
            index=models.Index(fields=["user", "status"], name="comp_assign_user_stat_idx"),
        ),
        migrations.AddConstraint(
            model_name="packinstallationconfigrevision",
            constraint=models.UniqueConstraint(
                fields=("installation", "version"),
                name="pack_config_revision_install_version_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="packinstallationconfigrevision",
            index=models.Index(fields=["company", "installation"], name="pack_config_company_inst_idx"),
        ),
        migrations.AddIndex(
            model_name="packinstallationconfigrevision",
            index=models.Index(fields=["organization", "created_at"], name="pack_config_org_created_idx"),
        ),
        migrations.AddConstraint(
            model_name="packnamespaceclaim",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("company", "namespaced_id"),
                name="pack_namespace_company_active_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="packnamespaceclaim",
            index=models.Index(fields=["company", "status"], name="pack_ns_comp_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="packnamespaceclaim",
            index=models.Index(fields=["installation", "status"], name="pack_ns_inst_stat_idx"),
        ),
        migrations.AddIndex(
            model_name="packnamespaceclaim",
            index=models.Index(fields=["pack_id", "object_type"], name="pack_namespace_pack_type_idx"),
        ),
    ]
