# Generated by Django 4.2.3 on 2026-05-12 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0082_company_pack_installations_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCatalogItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('internal', 'Internal'), ('organization', 'Organization'), ('customer', 'Customer'), ('public', 'Public')], default='organization', max_length=16)),
                ('audience', models.CharField(blank=True, default='', max_length=120)),
                ('required_pack_ids_json', models.JSONField(blank=True, default=list)),
                ('optional_pack_ids_json', models.JSONField(blank=True, default=list)),
                ('intake_schema_json', models.JSONField(blank=True, default=dict)),
                ('deliverables_schema_json', models.JSONField(blank=True, default=list)),
                ('default_operation_templates_json', models.JSONField(blank=True, default=list)),
                ('default_report_template_id', models.CharField(blank=True, default='', max_length=160)),
                ('pricing_metadata_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_catalog_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_catalog_items', to='orm.organization')),
            ],
            options={
                'db_table': 'service_catalog_items',
                'ordering': ['title', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ServiceEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('intake', 'Intake'), ('in_progress', 'In Progress'), ('waiting_on_customer', 'Waiting On Customer'), ('in_review', 'In Review'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='requested', max_length=32)),
                ('customer_status', models.CharField(choices=[('requested', 'Requested'), ('intake_needed', 'Intake Needed'), ('working', 'Working'), ('waiting_on_you', 'Waiting On You'), ('review_ready', 'Review Ready'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('intake_data_json', models.JSONField(blank=True, default=dict)),
                ('public_summary', models.TextField(blank=True, default='')),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('required_pack_ids_json', models.JSONField(blank=True, default=list)),
                ('operation_ids_json', models.JSONField(blank=True, default=list)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_engagements', to=settings.AUTH_USER_MODEL)),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='orm.servicecatalogitem')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_engagements', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_engagements', to='orm.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_service_engagements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_engagements',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceDeliverable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('deliverable_type', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('ready', 'Ready'), ('delivered', 'Delivered'), ('accepted', 'Accepted'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('visibility', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('internal', 'Internal')], default='customer', max_length=16)),
                ('summary', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deliverables', to='orm.asset')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_deliverables', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_deliverables', to=settings.AUTH_USER_MODEL)),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='orm.serviceengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_deliverables', to='orm.organization')),
                ('report_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deliverables', to='orm.reportrun')),
            ],
            options={
                'db_table': 'service_deliverables',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='serviceengagement',
            index=models.Index(fields=['organization', 'status'], name='svc_eng_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceengagement',
            index=models.Index(fields=['company', 'status'], name='svc_eng_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceengagement',
            index=models.Index(fields=['catalog_item', 'status'], name='svc_eng_catalog_status_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceengagement',
            index=models.Index(fields=['assigned_operator', 'status'], name='svc_eng_operator_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='serviceengagement',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key__gt', '')), fields=('company', 'source_key'), name='service_engagement_company_source_uniq'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['organization', 'status'], name='svc_deliv_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['company', 'status'], name='svc_deliv_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['engagement', 'status'], name='svc_deliv_eng_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['visibility', 'status'], name='svc_deliv_vis_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalogitem',
            index=models.Index(fields=['organization', 'status'], name='svc_catalog_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecatalogitem',
            index=models.Index(fields=['organization', 'visibility'], name='svc_catalog_org_vis_idx'),
        ),
        migrations.AddConstraint(
            model_name='servicecatalogitem',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='service_catalog_org_slug_uniq'),
        ),
    ]
