# Generated by Django 4.2.3 on 2026-05-14 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0084_toolexecution_results'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thread_type', models.CharField(choices=[('service_engagement', 'Service Engagement'), ('operation', 'Operation'), ('approval', 'Approval'), ('deliverable', 'Deliverable'), ('support', 'Support'), ('internal_handoff', 'Internal Handoff'), ('agent_collaboration', 'Agent Collaboration'), ('capability_gap', 'Capability Gap'), ('quality_gate', 'Quality Gate'), ('system_event', 'System Event')], default='support', max_length=32)),
                ('visibility_mode', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('internal', 'Internal'), ('mixed', 'Mixed')], default='mixed', max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_on_customer', 'Waiting On Customer'), ('waiting_on_operator', 'Waiting On Operator'), ('waiting_on_agent', 'Waiting On Agent'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='open', max_length=32)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.approvaltask')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.asset')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_threads', to='orm.graph')),
                ('created_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_threads', to='orm.agentregistryentry')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_communication_threads', to=settings.AUTH_USER_MODEL)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.run')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_threads', to='orm.organization')),
                ('report_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.reportrun')),
                ('service_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.serviceengagement')),
            ],
            options={
                'db_table': 'communication_threads',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_kind', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('company', 'Company'), ('organization', 'Organization'), ('system', 'System')], max_length=16)),
                ('message_kind', models.CharField(choices=[('note', 'Note'), ('request', 'Request'), ('response', 'Response'), ('status_update', 'Status Update'), ('approval_request', 'Approval Request'), ('decision', 'Decision'), ('deliverable', 'Deliverable'), ('capability_gap', 'Capability Gap'), ('handoff', 'Handoff'), ('missing_info_request', 'Missing Info Request'), ('system_event', 'System Event'), ('agent_observation', 'Agent Observation'), ('quality_gate_update', 'Quality Gate Update'), ('tool_result_summary', 'Tool Result Summary')], default='note', max_length=32)),
                ('body', models.TextField(blank=True, default='')),
                ('body_format', models.CharField(choices=[('plain', 'Plain'), ('markdown', 'Markdown'), ('structured_json', 'Structured JSON')], default='plain', max_length=16)),
                ('visibility', models.CharField(choices=[('customer', 'Customer'), ('operator', 'Operator'), ('internal', 'Internal')], default='customer', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('redacted_at', models.DateTimeField(blank=True, null=True)),
                ('redaction_reason', models.TextField(blank=True, default='')),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communication_messages', to='orm.organization')),
                ('sender_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to='orm.agentregistryentry')),
                ('sender_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communication_messages', to='orm.graph')),
                ('sender_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_communication_messages', to='orm.organization')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='orm.communicationthread')),
            ],
            options={
                'db_table': 'communication_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunicationAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.approvaltask')),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.asset')),
                ('artifact_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.assetversion')),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.decisionrecord')),
                ('evaluation_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.evaluationrun')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='orm.communicationmessage')),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.run')),
                ('report_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.reportrun')),
                ('service_deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.servicedeliverable')),
                ('service_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.serviceengagement')),
                ('signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.companysignal')),
                ('tool_execution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communication_attachments', to='orm.toolexecution')),
            ],
            options={
                'db_table': 'communication_attachments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['organization', 'company', 'updated_at'], name='comm_thread_org_comp_upd_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['organization', 'company', 'status', 'updated_at'], name='comm_thread_org_comp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['company', 'status', 'updated_at'], name='comm_thread_comp_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['service_engagement'], name='comm_thread_engage_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['operation'], name='comm_thread_operation_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['approval_task'], name='comm_thread_approval_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['artifact'], name='comm_thread_artifact_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['report_run'], name='comm_thread_report_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationthread',
            constraint=models.UniqueConstraint(condition=models.Q(('source_key__gt', '')), fields=('company', 'source_key'), name='comm_thread_company_source_uniq'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['thread', 'created_at'], name='comm_msg_thread_time_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['organization', 'company', 'created_at'], name='comm_msg_org_comp_time_idx'),
        ),
        migrations.AddIndex(
            model_name='communicationmessage',
            index=models.Index(fields=['thread', 'visibility', 'created_at'], name='comm_msg_thread_vis_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('thread', 'idempotency_key'), name='comm_msg_thread_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='communicationattachment',
            index=models.Index(fields=['message'], name='comm_attach_message_idx'),
        ),
    ]
