# Generated by Django 4.2.3 on 2026-05-14 03:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0085_communicationthread_communicationmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEventOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=128)),
                ('schema_version', models.CharField(max_length=64)),
                ('aggregate_type', models.CharField(max_length=64)),
                ('aggregate_id', models.UUIDField(db_index=True)),
                ('visibility', models.CharField(blank=True, default='', max_length=32)),
                ('topic', models.CharField(max_length=255)),
                ('payload_json', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed'), ('deferred', 'Deferred')], default='pending', max_length=16)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain_event_outbox', to='orm.graph')),
                ('domain_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='orm.domainevent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_event_outbox', to='orm.organization')),
            ],
            options={
                'db_table': 'domain_event_outbox',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='domain_outbox_due_idx'), models.Index(fields=['organization', 'status', 'created_at'], name='domain_outbox_org_status_idx'), models.Index(fields=['topic', 'status', 'created_at'], name='domain_outbox_topic_status_idx'), models.Index(fields=['event_type', 'created_at'], name='domain_outbox_type_time_idx'), models.Index(fields=['domain_event'], name='domain_outbox_event_idx')],
            },
        ),
    ]
