# Generated by Django 4.2.3 on 2026-05-14 22:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0086_domain_event_outbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('member', 'Member'), ('lead', 'Lead')], default='viewer', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'department_memberships',
                'ordering': ['department', 'user'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=160)),
                ('name', models.CharField(max_length=255)),
                ('department_type', models.CharField(blank=True, default='', max_length=64)),
                ('service_tags_json', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'department_registry',
                'ordering': ['name', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='RoutingPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(blank=True, default='', max_length=80)),
                ('channel', models.CharField(blank=True, default='', max_length=64)),
                ('signal_type', models.CharField(blank=True, default='', max_length=64)),
                ('entry_conditions_json', models.JSONField(blank=True, default=dict)),
                ('priority_rules_json', models.JSONField(blank=True, default=dict)),
                ('sla_json', models.JSONField(blank=True, default=dict)),
                ('required_approval_types_json', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routing_policies',
                'ordering': ['organization', '-active', 'service_type', 'channel'],
            },
        ),
        migrations.CreateModel(
            name='TaskRoutingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('sla_breached_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'task_routing_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_task_routing_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_routing_records', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='from_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_routing_records', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_routing_records', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='task_lifecycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.tasklifecyclerecord'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='to_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_routing_records', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='orm.graph'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_routing_policies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='fallback_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_routing_policies', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_policies', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='departmentregistry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_department_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to='orm.organization'),
        ),
        migrations.AddField(
            model_name='departmentmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communicationthread',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_threads', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='servicedeliverable',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_deliverables', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='tasklifecyclerecord',
            name='current_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_lifecycle_tasks', to='orm.departmentregistry'),
        ),
        migrations.AddField(
            model_name='taskrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_records', to='orm.departmentregistry'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['to_department', 'status', 'due_at'], name='task_routing_to_status_due_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['task_lifecycle', 'created_at'], name='task_route_life_time_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['status', 'sla_breached_at'], name='task_routing_sla_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['company', 'status', 'due_at'], name='task_routing_company_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['assigned_user', 'status', 'due_at'], name='task_routing_assignee_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['organization', 'company', 'service_type', 'active'], name='route_pol_org_comp_svc_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['department', 'active'], name='routing_policy_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['channel', 'active'], name='routing_policy_channel_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['signal_type', 'active'], name='routing_policy_signal_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentregistry',
            index=models.Index(fields=['organization', 'department_type', 'active'], name='dept_registry_org_type_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentregistry',
            index=models.Index(fields=['organization', 'active'], name='dept_registry_org_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentregistry',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='department_registry_org_slug_uniq'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['organization', 'status'], name='dept_member_org_status_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['department', 'role', 'status'], name='dept_member_dept_role_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['user', 'status'], name='dept_member_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='departmentmembership',
            index=models.Index(fields=['expires_at'], name='dept_member_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='departmentmembership',
            constraint=models.UniqueConstraint(fields=('department', 'user'), name='department_membership_dept_user_uniq'),
        ),
        migrations.AddIndex(
            model_name='communicationthread',
            index=models.Index(fields=['department', 'status'], name='comm_thread_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='servicedeliverable',
            index=models.Index(fields=['department', 'status'], name='svc_deliv_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='tasklifecyclerecord',
            index=models.Index(fields=['current_department', 'status'], name='task_life_dept_status_idx'),
        ),
        migrations.AddIndex(
            model_name='taskrecord',
            index=models.Index(fields=['department', 'status'], name='task_records_dept_status_idx'),
        ),
    ]
