# Generated by Django 4.2.3 on 2026-05-15 01:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0088_communicationeventreceipt'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='routingpolicy',
            name='route_pol_org_comp_svc_idx',
        ),
        migrations.AddField(
            model_name='departmentregistry',
            name='lead_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='event_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='routingpolicy',
            name='trigger_type',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='approval_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.approvaltask'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='communication_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.communicationmessage'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='communication_thread',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.communicationthread'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='company_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.companysignal'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.run'),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=16),
        ),
        migrations.AddField(
            model_name='taskroutingrecord',
            name='service_engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='routing_records', to='orm.serviceengagement'),
        ),
        migrations.AlterField(
            model_name='taskroutingrecord',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('assigned', 'Assigned'), ('claimed', 'Claimed'), ('in_progress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='queued', max_length=32),
        ),
        migrations.AlterField(
            model_name='taskroutingrecord',
            name='task_lifecycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_records', to='orm.tasklifecyclerecord'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['organization', 'company', 'trigger_type', 'active'], name='route_pol_org_comp_trig_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['event_type', 'active'], name='routing_policy_event_idx'),
        ),
        migrations.AddIndex(
            model_name='routingpolicy',
            index=models.Index(fields=['service_type', 'active'], name='routing_policy_svc_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['communication_thread', 'created_at'], name='task_route_comm_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['communication_message', 'created_at'], name='task_route_comm_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='taskroutingrecord',
            index=models.Index(fields=['idempotency_key'], name='task_routing_idem_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskroutingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('organization', 'idempotency_key'), name='task_routing_org_idem_uniq'),
        ),
    ]
