# Generated by Django 4.2.3 on 2026-05-15 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0089_remove_routingpolicy_route_pol_org_comp_svc_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkWhiteboard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('onboarding', 'Onboarding'), ('ready_for_strategy', 'Ready for strategy'), ('in_strategy', 'In strategy'), ('in_content', 'In content'), ('in_approval', 'In approval'), ('in_deployment', 'In deployment'), ('in_optimization', 'In optimization'), ('closed', 'Closed')], default='draft', max_length=32)),
                ('request_type', models.CharField(blank=True, default='', max_length=80)),
                ('client_name', models.CharField(blank=True, default='', max_length=255)),
                ('request_summary', models.TextField(blank=True, default='')),
                ('objective', models.TextField(blank=True, default='')),
                ('budget_limit', models.CharField(blank=True, default='', max_length=120)),
                ('timeline', models.CharField(blank=True, default='', max_length=255)),
                ('constraints_json', models.JSONField(blank=True, default=dict)),
                ('target_audience_json', models.JSONField(blank=True, default=dict)),
                ('brand_context_json', models.JSONField(blank=True, default=dict)),
                ('product_context_json', models.JSONField(blank=True, default=dict)),
                ('channel_context_json', models.JSONField(blank=True, default=dict)),
                ('known_facts_json', models.JSONField(blank=True, default=dict)),
                ('assumptions_json', models.JSONField(blank=True, default=list)),
                ('missing_fields_json', models.JSONField(blank=True, default=list)),
                ('completion_score', models.FloatField(default=0.0)),
                ('redis_snapshot_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_whiteboards', to='orm.communicationthread')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_whiteboards', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_whiteboards', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_whiteboards', to='orm.organization')),
                ('service_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_whiteboards', to='orm.serviceengagement')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_work_whiteboards', to='orm.communicationmessage')),
            ],
            options={
                'db_table': 'work_whiteboards',
            },
        ),
        migrations.CreateModel(
            name='RequestClassificationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('classification', models.CharField(choices=[('NEW_REQUEST', 'New request'), ('EXISTING_REQUEST', 'Existing request'), ('AMBIGUOUS_REQUEST', 'Ambiguous request')], max_length=32)),
                ('confidence', models.FloatField(default=0.0)),
                ('rationale', models.TextField(blank=True, default='')),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_classifications', to='orm.communicationmessage')),
                ('communication_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_classifications', to='orm.communicationthread')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_classifications', to='orm.graph')),
                ('matched_service_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_request_classifications', to='orm.serviceengagement')),
                ('matched_whiteboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_classifications', to='orm.workwhiteboard')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_classifications', to='orm.organization')),
                ('service_engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_classifications', to='orm.serviceengagement')),
            ],
            options={
                'db_table': 'request_classification_records',
            },
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['organization', 'company', 'status', 'updated_at'], name='whiteboard_org_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['company', 'status', 'updated_at'], name='whiteboard_comp_status_idx'),
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['communication_thread'], name='whiteboard_thread_idx'),
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['source_message'], name='whiteboard_source_msg_idx'),
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['service_engagement'], name='whiteboard_service_idx'),
        ),
        migrations.AddIndex(
            model_name='workwhiteboard',
            index=models.Index(fields=['idempotency_key'], name='whiteboard_idem_idx'),
        ),
        migrations.AddConstraint(
            model_name='workwhiteboard',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'idempotency_key'), name='uniq_whiteboard_org_idem_nonempty'),
        ),
        migrations.AddIndex(
            model_name='requestclassificationrecord',
            index=models.Index(fields=['organization', 'company', 'created_at'], name='req_class_org_comp_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestclassificationrecord',
            index=models.Index(fields=['communication_message', 'created_at'], name='req_class_msg_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestclassificationrecord',
            index=models.Index(fields=['classification', 'created_at'], name='req_class_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='requestclassificationrecord',
            index=models.Index(fields=['matched_whiteboard'], name='req_class_whiteboard_idx'),
        ),
        migrations.AddIndex(
            model_name='requestclassificationrecord',
            index=models.Index(fields=['idempotency_key'], name='req_class_idem_idx'),
        ),
        migrations.AddConstraint(
            model_name='requestclassificationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'idempotency_key'), name='uniq_req_class_org_idem_nonempty'),
        ),
    ]
