# Generated by Codex on 2026-05-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0090_workwhiteboard_requestclassificationrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskroutingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("assigned", "Assigned"),
                    ("claimed", "Claimed"),
                    ("in_progress", "In Progress"),
                    ("blocked", "Blocked"),
                    ("ready_for_review", "Ready For Review"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                ],
                default="queued",
                max_length=32,
            ),
        ),
    ]
