# Generated by Codex on 2026-05-31

from django.db import migrations, models


SIGNAL_TYPE_ALIASES = {
    "demand": ("opportunity", "general"),
    "lead": ("opportunity", "general"),
    "stockout": ("risk", "inventory"),
    "content_response": ("feedback", "content"),
    "fulfillment_issue": ("exception", "operations"),
    "paid_order": ("milestone", "commerce"),
    "manual": ("manual", "general"),
}

OPERATION_TYPE_ALIASES = {
    "daily_operating_brief": ("brief", "general"),
    "content_drop_planning": ("planning", "content"),
    "paid_order_follow_up": ("follow_up", "commerce"),
    "fulfillment_exception_review": ("exception_review", "operations"),
    "sold_out_demand_capture": ("evidence_capture", "inventory"),
    "reorder_procurement_approval": ("approval_request", "procurement"),
}


def backfill_generic_semantics(apps, schema_editor):
    CompanySignal = apps.get_model("orm", "CompanySignal")
    CompanyOperationObjective = apps.get_model("orm", "CompanyOperationObjective")

    for signal_type, (signal_kind, domain_context) in SIGNAL_TYPE_ALIASES.items():
        CompanySignal.objects.filter(signal_type=signal_type).update(
            signal_kind=signal_kind,
            domain_context=domain_context,
        )

    for objective in CompanyOperationObjective.objects.select_related("operation").iterator():
        input_json = objective.operation.input_json if objective.operation_id else {}
        if not isinstance(input_json, dict):
            input_json = {}
        operation_type = str(input_json.get("operation_type") or "")
        operation_family, domain_context = OPERATION_TYPE_ALIASES.get(
            operation_type,
            ("brief", "general"),
        )
        objective.operation_family = operation_family
        objective.domain_context = domain_context
        objective.save(update_fields=["operation_family", "domain_context"])


def reset_generic_semantics(apps, schema_editor):
    CompanySignal = apps.get_model("orm", "CompanySignal")
    CompanyOperationObjective = apps.get_model("orm", "CompanyOperationObjective")
    CompanySignal.objects.update(signal_kind="manual", domain_context="general")
    CompanyOperationObjective.objects.update(operation_family="brief", domain_context="general")


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0091_taskroutingrecord_ready_for_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="companysignal",
            name="signal_kind",
            field=models.CharField(
                choices=[
                    ("request", "Request"),
                    ("opportunity", "Opportunity"),
                    ("risk", "Risk"),
                    ("exception", "Exception"),
                    ("feedback", "Feedback"),
                    ("metric_change", "Metric Change"),
                    ("capability_gap", "Capability Gap"),
                    ("milestone", "Milestone"),
                    ("manual", "Manual"),
                ],
                default="manual",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="companysignal",
            name="domain_context",
            field=models.CharField(blank=True, default="general", max_length=64),
        ),
        migrations.AddField(
            model_name="companyoperationobjective",
            name="operation_family",
            field=models.CharField(
                choices=[
                    ("brief", "Brief"),
                    ("planning", "Planning"),
                    ("follow_up", "Follow Up"),
                    ("exception_review", "Exception Review"),
                    ("evidence_capture", "Evidence Capture"),
                    ("approval_request", "Approval Request"),
                ],
                default="brief",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="companyoperationobjective",
            name="domain_context",
            field=models.CharField(blank=True, default="general", max_length=64),
        ),
        migrations.RunPython(backfill_generic_semantics, reset_generic_semantics),
        migrations.AddIndex(
            model_name="companysignal",
            index=models.Index(
                fields=["company", "signal_kind"],
                name="company_signal_kind_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companyoperationobjective",
            index=models.Index(
                fields=["company", "operation_family"],
                name="company_obj_family_idx",
            ),
        ),
    ]
