# Generated by Codex on 2026-05-31

from django.db import migrations, models


LEGACY_STATUS_TO_WORK_STATUS = {
    "draft": "draft",
    "onboarding": "intake",
    "ready_for_strategy": "ready_for_planning",
    "in_strategy": "planning",
    "in_content": "in_progress",
    "in_approval": "review",
    "in_deployment": "delivery",
    "in_optimization": "measurement",
    "closed": "closed",
}

LEGACY_MISSING_FIELD_TO_WORK_FIELD = {
    "objective": "objective",
    "offer": "scope",
    "timeline": "timeline",
    "target_audience": "stakeholders",
    "brand_voice": "resources",
    "visual_constraints": "constraints",
    "legal_compliance_constraints": "constraints",
    "approval_owner": "approval_owner",
    "success_metrics": "success_metrics",
    "inventory_price_margin_constraints": "resources",
    "connector_readiness": "delivery_readiness",
}

WORK_REQUIRED_FIELDS = [
    "objective",
    "scope",
    "timeline",
    "stakeholders",
    "resources",
    "constraints",
    "approval_owner",
    "success_metrics",
    "delivery_readiness",
]


def _dict(value):
    return value if isinstance(value, dict) else {}


def _work_missing_fields(legacy_missing):
    seen = {
        LEGACY_MISSING_FIELD_TO_WORK_FIELD.get(str(field), str(field))
        for field in (legacy_missing if isinstance(legacy_missing, list) else [])
    }
    return [field for field in WORK_REQUIRED_FIELDS if field in seen]


def backfill_workboard_generic_semantics(apps, schema_editor):
    WorkWhiteboard = apps.get_model("orm", "WorkWhiteboard")

    for whiteboard in WorkWhiteboard.objects.select_related("company").iterator():
        target_audience = _dict(whiteboard.target_audience_json)
        product_context = _dict(whiteboard.product_context_json)
        brand_context = _dict(whiteboard.brand_context_json)
        channel_context = _dict(whiteboard.channel_context_json)
        resource_context = dict(product_context)
        if brand_context:
            resource_context["brand_context"] = dict(brand_context)
        company_name = getattr(whiteboard.company, "name", "") if whiteboard.company_id else ""
        whiteboard.work_status = LEGACY_STATUS_TO_WORK_STATUS.get(
            whiteboard.status or "",
            "draft",
        )
        whiteboard.project_name = str(whiteboard.client_name or company_name or "")[:255]
        whiteboard.stakeholder_context_json = target_audience
        whiteboard.resource_context_json = resource_context
        whiteboard.delivery_context_json = channel_context
        whiteboard.work_missing_fields_json = _work_missing_fields(whiteboard.missing_fields_json)
        whiteboard.save(
            update_fields=[
                "work_status",
                "project_name",
                "stakeholder_context_json",
                "resource_context_json",
                "delivery_context_json",
                "work_missing_fields_json",
            ]
        )


def reset_workboard_generic_semantics(apps, schema_editor):
    WorkWhiteboard = apps.get_model("orm", "WorkWhiteboard")
    WorkWhiteboard.objects.update(
        work_status="draft",
        project_name="",
        stakeholder_context_json={},
        resource_context_json={},
        delivery_context_json={},
        work_missing_fields_json=[],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0092_company_ops_generic_semantics"),
    ]

    operations = [
        migrations.AddField(
            model_name="workwhiteboard",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("intake", "Intake"),
                    ("ready_for_planning", "Ready for planning"),
                    ("planning", "Planning"),
                    ("in_progress", "In progress"),
                    ("review", "Review"),
                    ("delivery", "Delivery"),
                    ("measurement", "Measurement"),
                    ("closed", "Closed"),
                ],
                default="draft",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="workwhiteboard",
            name="project_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="workwhiteboard",
            name="stakeholder_context_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workwhiteboard",
            name="resource_context_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workwhiteboard",
            name="delivery_context_json",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="workwhiteboard",
            name="work_missing_fields_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(
            backfill_workboard_generic_semantics,
            reset_workboard_generic_semantics,
        ),
        migrations.AddIndex(
            model_name="workwhiteboard",
            index=models.Index(
                fields=["company", "work_status"],
                name="whiteboard_comp_work_stat_idx",
            ),
        ),
    ]
