# Generated by Codex on 2026-06-01

from __future__ import annotations

import uuid

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orm", "0093_workwhiteboard_generic_semantics"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOperation",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("kind", models.CharField(max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("blocked", "Blocked"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="accepted",
                        max_length=24,
                    ),
                ),
                ("target_type", models.CharField(max_length=80)),
                ("target_id", models.CharField(blank=True, default="", max_length=200)),
                ("idempotency_key", models.CharField(blank=True, default="", max_length=255)),
                ("contract_revision_at_accept", models.PositiveIntegerField(default=0)),
                ("contract_revision_at_completion", models.PositiveIntegerField(default=0)),
                ("error_code", models.CharField(blank=True, default="", max_length=120)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_operations",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_product_operations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_operations",
                        to="orm.organization",
                    ),
                ),
                (
                    "whiteboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="orm.workwhiteboard",
                    ),
                ),
            ],
            options={"db_table": "product_operations"},
        ),
        migrations.AddIndex(
            model_name="productoperation",
            index=models.Index(
                fields=["organization", "company", "whiteboard", "created_at"],
                name="prod_op_scope_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productoperation",
            index=models.Index(fields=["whiteboard", "status", "created_at"], name="prod_op_wb_status_idx"),
        ),
        migrations.AddIndex(
            model_name="productoperation",
            index=models.Index(
                fields=["whiteboard", "target_type", "target_id"],
                name="prod_op_wb_target_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productoperation",
            index=models.Index(fields=["idempotency_key"], name="prod_op_idem_idx"),
        ),
        migrations.AddConstraint(
            model_name="productoperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("idempotency_key__gt", "")),
                fields=("whiteboard", "kind", "target_type", "target_id", "idempotency_key"),
                name="uniq_prod_op_wb_kind_target_idem",
            ),
        ),
    ]
