# Generated by Django 6.0.4 on 2026-06-04 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0097_gateway_capabilities_media_schedules'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtlasLaunchAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('requested_mode', models.CharField(choices=[('dry_run', 'Dry Run'), ('live', 'Live')], default='dry_run', max_length=16)),
                ('status', models.CharField(choices=[('dry_run', 'Dry Run'), ('blocked', 'Blocked'), ('ready', 'Ready'), ('launched', 'Launched'), ('failed', 'Failed')], default='dry_run', max_length=16)),
                ('blocker_snapshot_json', models.JSONField(blank=True, default=list)),
                ('readiness_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('last_checkpoint_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_attempts', to='orm.graph')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_atlas_launch_attempts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_attempts', to='orm.organization')),
                ('receipt_deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlas_launch_attempts', to='orm.servicedeliverable')),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_attempts', to='orm.workwhiteboard')),
            ],
            options={
                'db_table': 'atlas_launch_attempts',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AtlasLaunchCheckpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('checkpoint_type', models.CharField(default='readiness_evaluated', max_length=80)),
                ('requested_mode', models.CharField(choices=[('dry_run', 'Dry Run'), ('live', 'Live')], max_length=16)),
                ('status', models.CharField(choices=[('dry_run', 'Dry Run'), ('blocked', 'Blocked'), ('ready', 'Ready'), ('launched', 'Launched'), ('failed', 'Failed')], max_length=16)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('source_key', models.CharField(max_length=255)),
                ('blocker_snapshot_json', models.JSONField(blank=True, default=list)),
                ('readiness_snapshot_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='orm.atlaslaunchattempt')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_checkpoints', to='orm.graph')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_checkpoints', to='orm.organization')),
                ('receipt_deliverable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atlas_launch_checkpoints', to='orm.servicedeliverable')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_atlas_launch_checkpoints', to=settings.AUTH_USER_MODEL)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atlas_launch_checkpoints', to='orm.workwhiteboard')),
            ],
            options={
                'db_table': 'atlas_launch_checkpoints',
                'ordering': ['attempt', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='atlaslaunchattempt',
            index=models.Index(fields=['organization', 'status'], name='atlas_launch_att_org_st_idx'),
        ),
        migrations.AddIndex(
            model_name='atlaslaunchattempt',
            index=models.Index(fields=['company', 'status'], name='atlas_launch_att_comp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='atlaslaunchattempt',
            index=models.Index(fields=['whiteboard', 'status'], name='atlas_launch_att_board_st_idx'),
        ),
        migrations.AddConstraint(
            model_name='atlaslaunchattempt',
            constraint=models.UniqueConstraint(fields=('company', 'source_key'), name='atlas_launch_att_comp_src_uniq'),
        ),
        migrations.AddConstraint(
            model_name='atlaslaunchattempt',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='atlas_launch_att_comp_idem_uniq'),
        ),
        migrations.AddIndex(
            model_name='atlaslaunchcheckpoint',
            index=models.Index(fields=['organization', 'created_at'], name='atlas_launch_cp_org_cr_idx'),
        ),
        migrations.AddIndex(
            model_name='atlaslaunchcheckpoint',
            index=models.Index(fields=['company', 'status'], name='atlas_launch_cp_comp_st_idx'),
        ),
        migrations.AddIndex(
            model_name='atlaslaunchcheckpoint',
            index=models.Index(fields=['whiteboard', 'created_at'], name='atlas_launch_cp_board_cr_idx'),
        ),
        migrations.AddConstraint(
            model_name='atlaslaunchcheckpoint',
            constraint=models.UniqueConstraint(fields=('attempt', 'sequence'), name='atlas_launch_cp_att_seq_uniq'),
        ),
    ]
