# Generated by Codex on 2026-06-04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0098_atlaslaunchattempt_atlaslaunchcheckpoint_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtlasReportingCadencePlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cadence_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("qbr", "Quarterly Business Review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("anchor_date", models.DateField(blank=True, null=True)),
                ("next_due_on", models.DateField()),
                (
                    "proof_template_id",
                    models.CharField(
                        blank=True,
                        default="atlas.proof_of_value",
                        max_length=160,
                    ),
                ),
                ("metadata_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atlas_reporting_cadence_plans",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_atlas_reporting_cadence_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "engagement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atlas_reporting_cadence_plans",
                        to="orm.serviceengagement",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atlas_reporting_cadence_plans",
                        to="orm.organization",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_reporting_cadence_plans",
                "ordering": ["company", "cadence_type"],
            },
        ),
        migrations.CreateModel(
            name="AtlasReportingCadenceRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "cadence_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("qbr", "Quarterly Business Review"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("generated", "Generated"), ("failed", "Failed")],
                        default="generated",
                        max_length=16,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255)),
                ("source_key", models.CharField(blank=True, default="", max_length=255)),
                ("due_on", models.DateField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("proof_snapshot_json", models.JSONField(blank=True, default=dict)),
                ("source_refs_json", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atlas_reporting_cadence_runs",
                        to="orm.graph",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_atlas_reporting_cadence_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atlas_reporting_cadence_runs",
                        to="orm.organization",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="orm.atlasreportingcadenceplan",
                    ),
                ),
                (
                    "report_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atlas_reporting_cadence_runs",
                        to="orm.reportrun",
                    ),
                ),
            ],
            options={
                "db_table": "atlas_reporting_cadence_runs",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="atlasreportingcadenceplan",
            name="last_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="orm.atlasreportingcadencerun",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadenceplan",
            index=models.Index(
                fields=["organization", "status"],
                name="atlas_report_plan_org_st_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadenceplan",
            index=models.Index(
                fields=["company", "cadence_type"],
                name="atlas_report_plan_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadenceplan",
            index=models.Index(
                fields=["company", "next_due_on"],
                name="atlas_report_plan_due_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="atlasreportingcadenceplan",
            constraint=models.UniqueConstraint(
                fields=("company", "cadence_type"),
                name="atlas_report_plan_comp_type_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadencerun",
            index=models.Index(
                fields=["organization", "created_at"],
                name="atlas_report_run_org_cr_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadencerun",
            index=models.Index(
                fields=["company", "cadence_type"],
                name="atlas_report_run_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadencerun",
            index=models.Index(
                fields=["company", "period_end"],
                name="atlas_report_run_period_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="atlasreportingcadencerun",
            index=models.Index(
                fields=["plan", "created_at"],
                name="atlas_report_run_plan_cr_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="atlasreportingcadencerun",
            constraint=models.UniqueConstraint(
                fields=("plan", "idempotency_key"),
                name="atlas_report_run_plan_idem_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="atlasreportingcadencerun",
            constraint=models.UniqueConstraint(
                fields=("plan", "due_on"),
                name="atlas_report_run_plan_due_uniq",
            ),
        ),
    ]
