# Generated by Django 6.0.4 on 2026-06-04 21:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0098_atlaslaunchattempt_atlaslaunchcheckpoint_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEngagementBusinessSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_key', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('revenue_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('delivery_cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pass_through_cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tooling_cost_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_margin_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_margin_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('profitability_band', models.CharField(choices=[('unknown', 'Unknown'), ('strong', 'Strong'), ('healthy', 'Healthy'), ('thin', 'Thin'), ('break_even', 'Break Even'), ('loss', 'Loss')], default='unknown', max_length=32)),
                ('scope_unit', models.CharField(blank=True, default='', max_length=64)),
                ('scope_included_units', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_used_units', models.PositiveIntegerField(blank=True, null=True)),
                ('scope_overage_units', models.PositiveIntegerField(default=0)),
                ('scope_utilization_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('scope_status', models.CharField(choices=[('unknown', 'Unknown'), ('on_track', 'On Track'), ('at_risk', 'At Risk'), ('over_limit', 'Over Limit')], default='unknown', max_length=32)),
                ('sla_target_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sla_elapsed_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sla_breach_count', models.PositiveIntegerField(default=0)),
                ('sla_status', models.CharField(choices=[('unknown', 'Unknown'), ('met', 'Met'), ('at_risk', 'At Risk'), ('breached', 'Breached')], default='unknown', max_length=32)),
                ('snapshot_json', models.JSONField(blank=True, default=dict)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_engagement_business_snapshots', to='orm.graph')),
                ('engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_snapshots', to='orm.serviceengagement')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_engagement_business_snapshots', to='orm.organization')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_service_engagement_business_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_engagement_business_snapshots',
                'ordering': ['-recorded_at', '-created_at'],
                'indexes': [models.Index(fields=['organization', 'recorded_at'], name='svc_bus_snap_org_time_idx'), models.Index(fields=['company', 'recorded_at'], name='svc_bus_snap_comp_time_idx'), models.Index(fields=['engagement', 'recorded_at'], name='svc_bus_snap_eng_time_idx'), models.Index(fields=['company', 'profitability_band'], name='svc_bus_snap_profit_idx'), models.Index(fields=['company', 'scope_status'], name='svc_bus_snap_scope_idx'), models.Index(fields=['company', 'sla_status'], name='svc_bus_snap_sla_idx')],
                'constraints': [models.UniqueConstraint(fields=('engagement', 'idempotency_key'), name='svc_bus_snap_eng_idem_uniq'), models.UniqueConstraint(condition=models.Q(('source_key__gt', '')), fields=('engagement', 'source_key'), name='svc_bus_snap_eng_src_uniq')],
            },
        ),
    ]
