# Generated by Hermes conflict resolution for Atlas steps 9-12 integration.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orm", "0099_atlas_reporting_cadence"),
        ("orm", "0099_service_engagement_business_snapshots"),
    ]

    operations = []
