#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ci/lib.sh
source "${SCRIPT_DIR}/lib.sh"

ROOT="$(forgegraph_repo_root)"
cd "${ROOT}"

bash "${SCRIPT_DIR}/check_live_playwright_no_mocks.sh"

cd "${ROOT}/frontend"
require_command npx

export PLAYWRIGHT_RUNTIME_TARGET="${PLAYWRIGHT_RUNTIME_TARGET:-local}"
export PLAYWRIGHT_WORKERS="${PLAYWRIGHT_WORKERS:-1}"
export PLAYWRIGHT_BACKEND_PORT="${PLAYWRIGHT_BACKEND_PORT:-8002}"
export PLAYWRIGHT_DEV_PORT="${PLAYWRIGHT_DEV_PORT:-3001}"
export PLAYWRIGHT_API_URL="${PLAYWRIGHT_API_URL:-http://127.0.0.1:${PLAYWRIGHT_BACKEND_PORT}}"
export NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-${PLAYWRIGHT_API_URL}}"
export USE_IN_MEMORY_CHANNEL_LAYER="${USE_IN_MEMORY_CHANNEL_LAYER:-false}"
export USE_IN_MEMORY_CACHE="${USE_IN_MEMORY_CACHE:-false}"
export PLAYWRIGHT_LOAD_SMOKE_RUNS="${PLAYWRIGHT_LOAD_SMOKE_RUNS:-100}"
export PLAYWRIGHT_LOAD_SMOKE_START_CONCURRENCY="${PLAYWRIGHT_LOAD_SMOKE_START_CONCURRENCY:-10}"
export PLAYWRIGHT_LLM_MOCK_ERROR_MODE="${PLAYWRIGHT_LLM_MOCK_ERROR_MODE:-off}"
export AUTH_REGISTER_THROTTLE_RATE="${AUTH_REGISTER_THROTTLE_RATE:-10000/min}"
export AUTH_LOGIN_THROTTLE_RATE="${AUTH_LOGIN_THROTTLE_RATE:-10000/min}"
export AUTH_REFRESH_THROTTLE_RATE="${AUTH_REFRESH_THROTTLE_RATE:-10000/min}"
export AUTH_WS_TICKET_THROTTLE_RATE="${AUTH_WS_TICKET_THROTTLE_RATE:-10000/min}"
export API_ANON_THROTTLE_RATE="${API_ANON_THROTTLE_RATE:-10000/min}"
export API_USER_THROTTLE_RATE="${API_USER_THROTTLE_RATE:-10000/min}"
export RUN_START_RATE_LIMIT_PER_MIN="${RUN_START_RATE_LIMIT_PER_MIN:-10000}"
export RUN_INVOKE_RATE_LIMIT_PER_MIN="${RUN_INVOKE_RATE_LIMIT_PER_MIN:-10000}"
export RUN_MAX_ACTIVE_PER_TENANT="${RUN_MAX_ACTIVE_PER_TENANT:-250}"
export RUN_QUEUE_MAX_CONCURRENCY_PER_TENANT="${RUN_QUEUE_MAX_CONCURRENCY_PER_TENANT:-100}"

if [[ "${ROOT}" == /mnt/* ]] && command -v cmd.exe >/dev/null 2>&1; then
  wsl_env_names=(
    PLAYWRIGHT_RUNTIME_TARGET
    PLAYWRIGHT_WORKERS
    PLAYWRIGHT_BACKEND_PORT
    PLAYWRIGHT_DEV_PORT
    PLAYWRIGHT_API_URL
    NEXT_PUBLIC_API_URL
    USE_IN_MEMORY_CHANNEL_LAYER
    USE_IN_MEMORY_CACHE
    PLAYWRIGHT_LOAD_SMOKE_RUNS
    PLAYWRIGHT_LOAD_SMOKE_START_CONCURRENCY
    PLAYWRIGHT_LLM_MOCK_ERROR_MODE
    AUTH_REGISTER_THROTTLE_RATE
    AUTH_LOGIN_THROTTLE_RATE
    AUTH_REFRESH_THROTTLE_RATE
    AUTH_WS_TICKET_THROTTLE_RATE
    API_ANON_THROTTLE_RATE
    API_USER_THROTTLE_RATE
    RUN_START_RATE_LIMIT_PER_MIN
    RUN_INVOKE_RATE_LIMIT_PER_MIN
    RUN_MAX_ACTIVE_PER_TENANT
    RUN_QUEUE_MAX_CONCURRENCY_PER_TENANT
  )
  IFS=:
  export WSLENV="${wsl_env_names[*]}${WSLENV:+:${WSLENV}}"
  unset IFS
fi

run_npx() {
  if [[ "${ROOT}" == /mnt/* ]] && command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c npx "$@"
    return
  fi
  npx "$@"
}

log_section "100-concurrent no-LLM load smoke"
run_npx playwright test __tests__/e2e/load-smoke-live.spec.ts --project=chromium
