#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ci/lib.sh
source "${SCRIPT_DIR}/lib.sh"

ROOT="$(forgegraph_repo_root)"
cd "${ROOT}/frontend"

require_command npx

export PLAYWRIGHT_RUNTIME_TARGET="local"
export PLAYWRIGHT_WORKERS="${MOCKED_PLAYWRIGHT_WORKERS:-1}"
export PLAYWRIGHT_BACKEND_PORT="${PLAYWRIGHT_BACKEND_PORT:-8002}"
export PLAYWRIGHT_DEV_PORT="${PLAYWRIGHT_DEV_PORT:-3001}"
export PLAYWRIGHT_MEMORY_GRPC_PORT="${PLAYWRIGHT_MEMORY_GRPC_PORT:-50072}"
export MEMORY_GRPC_PORT="${MEMORY_GRPC_PORT:-${PLAYWRIGHT_MEMORY_GRPC_PORT}}"
export PLAYWRIGHT_API_URL="http://127.0.0.1:${PLAYWRIGHT_BACKEND_PORT}"
export NEXT_PUBLIC_API_URL="${PLAYWRIGHT_API_URL}"
export PLAYWRIGHT_AUTH_REGISTER_THROTTLE_RATE="${PLAYWRIGHT_AUTH_REGISTER_THROTTLE_RATE:-10000/min}"
export PLAYWRIGHT_AUTH_LOGIN_THROTTLE_RATE="${PLAYWRIGHT_AUTH_LOGIN_THROTTLE_RATE:-10000/min}"
export PLAYWRIGHT_AUTH_REFRESH_THROTTLE_RATE="${PLAYWRIGHT_AUTH_REFRESH_THROTTLE_RATE:-10000/min}"
export PLAYWRIGHT_AUTH_WS_TICKET_THROTTLE_RATE="${PLAYWRIGHT_AUTH_WS_TICKET_THROTTLE_RATE:-10000/min}"
export AUTH_REGISTER_THROTTLE_RATE="${PLAYWRIGHT_AUTH_REGISTER_THROTTLE_RATE}"
export AUTH_LOGIN_THROTTLE_RATE="${PLAYWRIGHT_AUTH_LOGIN_THROTTLE_RATE}"
export AUTH_REFRESH_THROTTLE_RATE="${PLAYWRIGHT_AUTH_REFRESH_THROTTLE_RATE}"
export AUTH_WS_TICKET_THROTTLE_RATE="${PLAYWRIGHT_AUTH_WS_TICKET_THROTTLE_RATE}"
export API_ANON_THROTTLE_RATE="${API_ANON_THROTTLE_RATE:-10000/min}"
export API_USER_THROTTLE_RATE="${API_USER_THROTTLE_RATE:-10000/min}"

if [[ "${ROOT}" == /mnt/* ]] && command -v cmd.exe >/dev/null 2>&1; then
  wsl_env_names=(
    PLAYWRIGHT_RUNTIME_TARGET
    PLAYWRIGHT_WORKERS
    PLAYWRIGHT_BACKEND_PORT
    PLAYWRIGHT_DEV_PORT
    PLAYWRIGHT_MEMORY_GRPC_PORT
    MEMORY_GRPC_PORT
    PLAYWRIGHT_API_URL
    NEXT_PUBLIC_API_URL
    PLAYWRIGHT_AUTH_REGISTER_THROTTLE_RATE
    PLAYWRIGHT_AUTH_LOGIN_THROTTLE_RATE
    PLAYWRIGHT_AUTH_REFRESH_THROTTLE_RATE
    PLAYWRIGHT_AUTH_WS_TICKET_THROTTLE_RATE
    AUTH_REGISTER_THROTTLE_RATE
    AUTH_LOGIN_THROTTLE_RATE
    AUTH_REFRESH_THROTTLE_RATE
    AUTH_WS_TICKET_THROTTLE_RATE
    API_ANON_THROTTLE_RATE
    API_USER_THROTTLE_RATE
  )
  IFS=:
  export WSLENV="${wsl_env_names[*]}${WSLENV:+:${WSLENV}}"
  unset IFS
fi

run_npx() {
  if [[ "${ROOT}" == /mnt/* ]] && command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c npx "$@"
    return
  fi
  npx "$@"
}

log_section "Mocked Playwright coverage"
run_npx playwright test \
  __tests__/e2e/control-surface-mocked.spec.ts \
  __tests__/e2e/operations.spec.ts \
  __tests__/e2e/realtime.spec.ts \
  --workers="${PLAYWRIGHT_WORKERS}" \
  --project=chromium
