#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=scripts/ci/lib.sh
source "${SCRIPT_DIR}/lib.sh"

ROOT="$(forgegraph_repo_root)"
cd "${ROOT}"

bash "${SCRIPT_DIR}/check_live_playwright_no_mocks.sh"

cd "${ROOT}/frontend"
require_command npx

export PLAYWRIGHT_RUNTIME_TARGET="${PLAYWRIGHT_RUNTIME_TARGET:-local}"
export PLAYWRIGHT_WORKERS="${PLAYWRIGHT_WORKERS:-1}"
export USE_IN_MEMORY_CHANNEL_LAYER="${USE_IN_MEMORY_CHANNEL_LAYER:-false}"
export USE_IN_MEMORY_CACHE="${USE_IN_MEMORY_CACHE:-false}"
export PLAYWRIGHT_LOAD_SMOKE_RUNS="${PLAYWRIGHT_LOAD_SMOKE_RUNS:-100}"
export PLAYWRIGHT_LOAD_SMOKE_START_CONCURRENCY="${PLAYWRIGHT_LOAD_SMOKE_START_CONCURRENCY:-10}"
export PLAYWRIGHT_LLM_MOCK_ERROR_MODE="${PLAYWRIGHT_LLM_MOCK_ERROR_MODE:-off}"
export AUTH_REGISTER_THROTTLE_RATE="${AUTH_REGISTER_THROTTLE_RATE:-10000/min}"
export AUTH_LOGIN_THROTTLE_RATE="${AUTH_LOGIN_THROTTLE_RATE:-10000/min}"
export AUTH_REFRESH_THROTTLE_RATE="${AUTH_REFRESH_THROTTLE_RATE:-10000/min}"
export AUTH_WS_TICKET_THROTTLE_RATE="${AUTH_WS_TICKET_THROTTLE_RATE:-10000/min}"
export API_ANON_THROTTLE_RATE="${API_ANON_THROTTLE_RATE:-10000/min}"
export API_USER_THROTTLE_RATE="${API_USER_THROTTLE_RATE:-10000/min}"
export RUN_START_RATE_LIMIT_PER_MIN="${RUN_START_RATE_LIMIT_PER_MIN:-10000}"
export RUN_INVOKE_RATE_LIMIT_PER_MIN="${RUN_INVOKE_RATE_LIMIT_PER_MIN:-10000}"
export RUN_MAX_ACTIVE_PER_TENANT="${RUN_MAX_ACTIVE_PER_TENANT:-250}"
export RUN_QUEUE_MAX_CONCURRENCY_PER_TENANT="${RUN_QUEUE_MAX_CONCURRENCY_PER_TENANT:-100}"

log_section "100-concurrent no-LLM load smoke"
npx playwright test __tests__/e2e/load-smoke-live.spec.ts --project=chromium
