# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EngineServiceStub(object):
    """EngineService provides core ForgeGraph engine operations
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/engine.EngineService/Ping',
                request_serializer=engine__pb2.PingRequest.SerializeToString,
                response_deserializer=engine__pb2.PingResponse.FromString,
                _registered_method=True)
        self.StartRun = channel.unary_unary(
                '/engine.EngineService/StartRun',
                request_serializer=engine__pb2.StartRunRequest.SerializeToString,
                response_deserializer=engine__pb2.StartRunResponse.FromString,
                _registered_method=True)
        self.GetRunStatus = channel.unary_unary(
                '/engine.EngineService/GetRunStatus',
                request_serializer=engine__pb2.GetRunStatusRequest.SerializeToString,
                response_deserializer=engine__pb2.GetRunStatusResponse.FromString,
                _registered_method=True)
        self.CancelRun = channel.unary_unary(
                '/engine.EngineService/CancelRun',
                request_serializer=engine__pb2.CancelRunRequest.SerializeToString,
                response_deserializer=engine__pb2.CancelRunResponse.FromString,
                _registered_method=True)
        self.ResumeRun = channel.unary_unary(
                '/engine.EngineService/ResumeRun',
                request_serializer=engine__pb2.ResumeRunRequest.SerializeToString,
                response_deserializer=engine__pb2.ResumeRunResponse.FromString,
                _registered_method=True)


class EngineServiceServicer(object):
    """EngineService provides core ForgeGraph engine operations
    """

    def Ping(self, request, context):
        """Ping returns a pong response for health checking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRun(self, request, context):
        """StartRun begins executing a workflow graph
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatus(self, request, context):
        """GetRunStatus returns the current status of a run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRun(self, request, context):
        """CancelRun cancels an active run
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResumeRun(self, request, context):
        """ResumeRun resumes a paused run (e.g., after human gate approval)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EngineServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=engine__pb2.PingRequest.FromString,
                    response_serializer=engine__pb2.PingResponse.SerializeToString,
            ),
            'StartRun': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRun,
                    request_deserializer=engine__pb2.StartRunRequest.FromString,
                    response_serializer=engine__pb2.StartRunResponse.SerializeToString,
            ),
            'GetRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatus,
                    request_deserializer=engine__pb2.GetRunStatusRequest.FromString,
                    response_serializer=engine__pb2.GetRunStatusResponse.SerializeToString,
            ),
            'CancelRun': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRun,
                    request_deserializer=engine__pb2.CancelRunRequest.FromString,
                    response_serializer=engine__pb2.CancelRunResponse.SerializeToString,
            ),
            'ResumeRun': grpc.unary_unary_rpc_method_handler(
                    servicer.ResumeRun,
                    request_deserializer=engine__pb2.ResumeRunRequest.FromString,
                    response_serializer=engine__pb2.ResumeRunResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.EngineService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.EngineService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EngineService(object):
    """EngineService provides core ForgeGraph engine operations
    """

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/Ping',
            engine__pb2.PingRequest.SerializeToString,
            engine__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/StartRun',
            engine__pb2.StartRunRequest.SerializeToString,
            engine__pb2.StartRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/GetRunStatus',
            engine__pb2.GetRunStatusRequest.SerializeToString,
            engine__pb2.GetRunStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/CancelRun',
            engine__pb2.CancelRunRequest.SerializeToString,
            engine__pb2.CancelRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResumeRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.EngineService/ResumeRun',
            engine__pb2.ResumeRunRequest.SerializeToString,
            engine__pb2.ResumeRunResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MemoryServiceStub(object):
    """MemoryService provides semantic memory retrieval for Tier 3.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrieveMemory = channel.unary_unary(
                '/engine.MemoryService/RetrieveMemory',
                request_serializer=engine__pb2.RetrieveMemoryRequest.SerializeToString,
                response_deserializer=engine__pb2.RetrieveMemoryResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer(object):
    """MemoryService provides semantic memory retrieval for Tier 3.
    """

    def RetrieveMemory(self, request, context):
        """RetrieveMemory returns relevant memory chunks for a query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveMemory,
                    request_deserializer=engine__pb2.RetrieveMemoryRequest.FromString,
                    response_serializer=engine__pb2.RetrieveMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'engine.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('engine.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService(object):
    """MemoryService provides semantic memory retrieval for Tier 3.
    """

    @staticmethod
    def RetrieveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/engine.MemoryService/RetrieveMemory',
            engine__pb2.RetrieveMemoryRequest.SerializeToString,
            engine__pb2.RetrieveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
